invenio_app_rdm/version.py, setup.py
- Upgrades invenio-rdm-records version
=> Release v1.0.0a3

invenio_app_rdm/config.py
- Grouped configuration
- Added documentation links
- Kept ad-hoc order of groups but sorted alphabetically
within a group
- Removed some configurations that repeated defaults
already provided by modules
- Closes: #27
=> config: organize config.py [more]

invenio_app_rdm/config.py, invenio_app_rdm/theme/assets/scss/invenio_app_rdm/footer.scss, invenio_app_rdm/theme/assets/scss/invenio_app_rdm/theme.scss, invenio_app_rdm/theme/static/templates/invenio_app_rdm/results.html, invenio_app_rdm/theme/templates/invenio_app_rdm/footer.html, invenio_app_rdm/theme/templates/invenio_app_rdm/page.html, invenio_app_rdm/theme/templates/invenio_app_rdm/record_view_page.html, invenio_app_rdm/theme/templates/invenio_app_rdm/search.html, invenio_app_rdm/theme/views.py, setup.py
=> ui: provide default record page

invenio_app_rdm/config.py, invenio_app_rdm/theme/templates/invenio_app_rdm/record_view_page.html
- Provide downloadable link
- Stopgap until resource type is made required
- close #42 
(will fail until invenio-records-permissions is released)
=> ui: list files on record page [more]

invenio_app_rdm/config.py, setup.py
Changes:
Add records-files config to overwrite default and allow the registration of the url.
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/54
=> config: add record-files rest endpoint

invenio_app_rdm/version.py
Changes:
* Release with new versioning scheme
Requires: https://github.com/inveniosoftware/invenio-rdm-records/pull/60
Might require: https://github.com/inveniosoftware/invenio-app-rdm/pull/62 (for releasing)
Closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/55
=> global: new versioning scheme

invenio_app_rdm/version.py, setup.py
- bump dependencies
- bump version
=> Release v0.7.0

invenio_app_rdm/theme/assets/scss/invenio_app_rdm/footer.scss, invenio_app_rdm/theme/assets/scss/invenio_app_rdm/theme.scss
=> ui: make footer stick to the bottom

invenio_app_rdm/theme/assets/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/TitlesField.js
Closes https://github.com/inveniosoftware/react-invenio-deposit/issues/2
=> [follows from #114] Fix initial null controlled value

invenio_app_rdm/theme/assets/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/AccessRightField.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/index.js, invenio_app_rdm/theme/assets/js/react_invenio_forms/core/RadioField.js, invenio_app_rdm/theme/assets/js/react_invenio_forms/core/index.js, invenio_app_rdm/theme/views.py, setup.py
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/18
will fail pending release of invenio-rdm-records==0.12.0
=> Add access right component

invenio_app_rdm/theme/assets/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/DepositApiClient.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/DepositController.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/DepositErrorHandler.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/DepositFormApp.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/DepositRecordSerializer.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/ContributorsField.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/CreatorOrContributorField.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/CreatorsField.js, invenio_app_rdm/theme/assets/js/react_invenio_deposit/state/actions/deposit.js
=> deposit: refactor publish flow

invenio_app_rdm/theme/templates/invenio_app_rdm/frontpage.html
Now the content is centered.
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/149
=> WIP templates: frontpage center alignment

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, invenio_app_rdm/theme/templates/invenio_app_rdm/header.html
=> frontpage: fix header link styling

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less
=> signup: make signup button colour consistent

invenio_app_rdm/theme/templates/invenio_app_rdm/footer.html, invenio_app_rdm/theme/templates/invenio_app_rdm/header.html
=> ui: fix alignment (search-bar + powered-by)

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, invenio_app_rdm/theme/templates/invenio_app_rdm/header.html, invenio_app_rdm/theme/views.py
=> header: left align nav items

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
- Inject a list of languages for the language dropdown
- Add the CreatorsField and ContributorsField back minus affiliations/identifiers subfields. I will do a write-up on identifier woes.
- requires https://github.com/inveniosoftware/react-invenio-deposit/pull/36 to be merged and released
=> deposit: Various fixes for #154

invenio_app_rdm/theme/templates/invenio_app_rdm/header.html
=> header: fix logo navigating to main page

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search_app_customizations.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less, invenio_app_rdm/theme/templates/invenio_app_rdm/header.html, invenio_app_rdm/theme/templates/invenio_app_rdm/header_frontpage.html
Depends on https://github.com/inveniosoftware/invenio-theme/pull/180
=> theme: sets search button color to RDM color

invenio_app_rdm/version.py, setup.py
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/204
=> Release 0.9.8

invenio_app_rdm/theme/webpack.py, invenio_app_rdm/version.py, setup.py
will merge when CI is good. Just keeping you in the loop,
=> Release v0.10.0

.tx/config, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/frontpage.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_frontpage.html, invenio_app_rdm/translations/messages.pot, invenio_app_rdm/translations/tr/LC_MESSAGES/messages.po, run-tests.sh
* marked strings for translation on frontpage.html and  header_frontpage.html
* changed transifex config file
* recreated .pot file
=> Frontpage translation

invenio_app_rdm/theme/webpack.py, invenio_app_rdm/version.py, setup.py
Bumping dependencies + release
=> Release v0.11.1

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/views.py, setup.py, tests/api/test_record_api.py
Sets up the August release by accounting for breaking changes.
This is part of making a working August release and will be merged and deployed when it passes.
=> Setup august release

invenio_app_rdm/theme/static/images/invenio-rdm.svg
* Edits RDM logo to delete
unnecessary left space
(blank space that was deleted, to align it correctly with the rest of the page)
Issue: https://github.com/inveniosoftware/invenio-app-rdm/issues/235
=> logo: Edits RDM logo

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/frontpage.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/frontpage.html
* Adds more whitespace on top
of headers
* Aligns the box texts and adds
some line spacing
* closes #237
=> styles: Frontpage alignment

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
=> hover: Adds hover to navbar items

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositResults.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositSearchApp.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search_app_customizations.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/deposits/uploads.html, invenio_app_rdm/theme/webpack.py
closes #242
- `invenio-search-ui`'s webpack.py needs:
```diff
diff --git a/invenio_search_ui/webpack.py b/invenio_search_ui/webpack.py
index cc9bc58..48e0135 100644
--- a/invenio_search_ui/webpack.py
+++ b/invenio_search_ui/webpack.py
@@ -45,6 +45,10 @@ search_ui = WebpackThemeBundle(
"semantic-ui-react": "^0.88.0",
"@babel/runtime": "^7.9.0",
},
+            aliases={
+                '@templates': 'templates',
+                '@js/invenio_search_ui': 'js/invenio_search_ui',
+            }
),
"bootstrap3": dict(
entry={
```
=> deposits: add deposits search app and customization

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/search_app_common_customizations.js
closes #243 
Please give your feedback on what can be added/removed/improved.
Updated Screenshot:
=> react-templates: Add common template for main and community search

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/252
=> styles: Fix menu hover

setup.py
Updating dependencies. Merging when passes. Necessary for https://github.com/inveniosoftware/invenio-app-rdm/pull/253 to pass.
=> dependencies: remove idna, bump rdm-records

.github/workflows/pypi-release.yml, .travis.yml, MANIFEST.in
**IMPORTANT**
This required setting a TOKEN with the name pypi_token in the repo, or using an organizational token. See more at: https://codimd.web.cern.ch/_wtkZy6MR5ad69HQeERJaA?view
Closes https://github.com/inveniosoftware/invenio/issues/4036 (demonstrator)
=> ci: release using gh actions

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/search.html
=> search: adapt to new API output

invenio_app_rdm/theme/views.py, invenio_app_rdm/theme/webpack.py, invenio_app_rdm/version.py, setup.py, tests/ui/test_configuration.py
=> blueprint: make UI urls configurable

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/search.html, setup.py
just bringing the facets we disabled back:
closes #279
=> search: re-enable faceting

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/deposits/uploads.html, invenio_app_rdm/theme/views.py, invenio_app_rdm/version.py, setup.py
Depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/188
=> User records page for searching in user's drafts

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search/components.js
=> search: default access set to open

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search/index.js, invenio_app_rdm/version.py
Depends on https://github.com/inveniosoftware/invenio-search-ui/pull/100
=> Fix uploads searchbar

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/search.html
Depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/195
=> search: add access-right ui customization

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/index.js
Depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/198
=> Facets ui config

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/search.html
* Adds missing values to render sort options and pagination size
* Closes #309
=> views: fixes React-Searchkit configuration

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/search.html
* Addresses https://github.com/inveniosoftware/invenio-rdm-records/issues/202
=> search: adds nested buckets in facets

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
Depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/211
Depends on https://github.com/inveniosoftware/marshmallow-utils/pull/18
=> search: show localized pub date

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/index.js
=> Bucket doc count

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
=> ui: add margin for top header

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/index.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/334
* Addresses https://github.com/inveniosoftware/invenio-app-rdm/issues/333
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/327
=> Add header shadow and enhance result templates

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/webpack.py
Depends on https://github.com/inveniosoftware/react-invenio-deposit/pull/69
=> deposit: add description/additional description field

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
- closes #10 
- needs https://github.com/inveniosoftware/react-invenio-deposit/pull/70
=> deposit: add publication date

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
Depends on https://github.com/inveniosoftware/react-invenio-deposit/pull/71
=> deposit: add Publisher field

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
* Uses smaller font for the publication
=> search: uses localized publication date

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
* Keeps facets from moving when searching
=> search: styles search options

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/search.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/357
=> ui: fix facet spacing

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/footer.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/footer.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/256
Current code:
Example with according to issue:
More zoom to display the shadow:
=> ui: make two level footer

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search/index.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/deposits/uploads.html
=> uploads: fixes UI according latest metadata and adds latest record facets

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less
* Shows orcid logo if identifier is present
* Closes #369
=> search: shows multiple creators

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
- closes https://github.com/inveniosoftware/react-invenio-deposit/issues/16
- requires: https://github.com/inveniosoftware/react-invenio-deposit/pull/80
=> deposit: add FundingField

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
- closes #13 
- requires https://github.com/inveniosoftware/react-invenio-deposit/pull/81
=> deposit: add VersionField

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
Depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/259
=> search: adjusts search results to the latest serializer changes

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/index.js
=> search: fix searchbar issue

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/footer.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
=> ui: fix footer to stick to bottom

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
Addresses the second part of https://github.com/inveniosoftware/invenio-app-rdm/issues/392
=> search: renders description html in results

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/386
=> search: fixes author orcid icon positioning in results

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
Depends on https://github.com/inveniosoftware/react-invenio-deposit/pull/108
=> theme: style file uploader

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/webpack.py
- requires: https://github.com/inveniosoftware/react-invenio-deposit/pull/112
=> deposit: use CreatibutorsField (update Creators/Contributors)

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/views.py, invenio_app_rdm/theme/webpack.py
- requires: react-invenio-deposit v0.10.0 (https://github.com/inveniosoftware/react-invenio-deposit/pull/153)
- the initial record was serialized without its links
* we have to be careful about our interfaces
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/452
=> deposit: add DeleteButton + fix record serialization [+]

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
- closes #468 
- fixes a missing `Grid,Row` that was causing some subtle layout issues for a long time
**Screenshots&&
=> deposit: stickify deposit form sidebar

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
=> deposit: place DepositFormTitle

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/463
requires https://github.com/inveniosoftware/react-invenio-deposit/pull/161
=> theme: change license add buttons css rules

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/123
=> deposit: center files pending label

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less
requires https://github.com/inveniosoftware/invenio-theme/pull/235
=> deposit: set accordion style

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/landing_page/details/details.html
- closes https://github.com/inveniosoftware/react-invenio-deposit/issues/86 (part 2)
=> deposit: display related work(s) consistently

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less
styles helptext in https://github.com/inveniosoftware/react-invenio-deposit/pull/175
=> deposit: style helptext

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less
=> deposit: offset sticky sidebar

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less
- close #480
- requires https://github.com/inveniosoftware/react-invenio-deposit/pull/177
**Screenshots**
=> deposit: mark Identifiers|Subjects|Funding fields as coming soon

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/deposits/uploads.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/landing_page/macros/creatibutors.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/search.html, invenio_app_rdm/theme/webpack.py
closes inveniosoftware/react-invenio-deposit#154
=> deposit: creators component refactor

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
=> misc january form improvements

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
Requires https://github.com/inveniosoftware/invenio-rdm-records/pull/345
=> ui: fix license field path and header in deposit form

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
=> deposit: fix related work spelling

invenio_app_rdm/version.py
will merge and release immediately - this is to get the typo fixes into the February release.
=> release: v0.19.9

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
=> disable: versions filter(toggle)

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less
closes inveniosoftware/react-invenio-deposit/issues/186
=> style: helptext label style

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less
css: changed from inline to inline-grid
closes #506
=> bugfix: landing page show affiliations

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/navbar.less
=> bugfix: menu hover fill the entire header

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
temporary remove fields from deposit 
* IdentifiersField
* Subjects
* FundingField
closes #522 
*screenshot*
=> deposit: temp removed fields

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/landing_page/macros/files.html
icons: change icons to semantic UI angle 'down right'
js: added toggle func to change the class
closes #509 
*screenshots*
=> bugfix: adding missing icon for preview file.

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/510
requires https://github.com/inveniosoftware/invenio-theme/pull/238
=> header: fix breadcrumbs style

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.html, invenio_app_rdm/theme/views.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/513
=> views: add search help page

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/index.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/deposits/uploads.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/search.html
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/354
=> templates: fix sort options

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/index.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/514
=> uploads: remove extra white space below header

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/recordManagement.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/navbar.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/landing_page/record_landing_page.html
* removed class ```padded```  - the padding were in conflict with ```ui container```
* target bottom padding ```ui.flashed.message``` for landing page - recordMangement.
* removed ```navbar-item.navbar-button``` css, to make alignment correct with the body.
closes #517
*screenshots*
=> styling: alignment landingpage & header btn

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/index.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
requires https://github.com/inveniosoftware/invenio-theme/pull/241
requires https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/138
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/515
=> deposit: restyle user uploads page

MANIFEST.in, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/form.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/form.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/message.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/message.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/button.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/button.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/header.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/header.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/icon.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/icon.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/input.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/input.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/segment.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/segment.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/reset.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/reset.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/checkbox.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/checkbox.variables, invenio_app_rdm/theme/webpack.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/546
=> theme: add rdm SUI packaged theme

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
- part of closing inveniosoftware/react-invenio-deposit#195
=> deposit: pass isPublished to title component

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/index.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/526
=> User search bottom row

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/list.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/list.variables
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/194
=> theme: move license styling to rdm theme

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less
=> DepositForm: add license links

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/recordManagement.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/header.overrides
when setting the header (flash error messages) sticky on top, it interact with sidebar sticky bar (protection widget), for the time being  the increase to `offset` for sidebar Sticky will do it. but should find a better way to deal with this.
closes #534 
*screenshot*
=> deposit: sticky error messages

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less
- expand it
- style some card
- part of #218
=> deposit: format sidebar [+]

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/list.overrides, setup.py, tests/conftest.py
part of closing https://github.com/inveniosoftware/react-invenio-deposit/issues/218
=> deposit: format disabled in sidebar

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html, invenio_app_rdm/version.py, setup.py
closes #562 
**screenshots**
*uploads page*
*search page*
=> bugfix: consistent spacing on search/uploads

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less
=> bugfix: label whitespace

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
=> contact-btn: removed

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search_deposit.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js
=> deposit: add ui fixes in user records search page

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search_deposit.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js
=> access-right: disabled access-right badges

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/index.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/list.overrides
=> deposit: fix user records search page top extra space

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/navbar.less
This happened after bugfix here:https://github.com/inveniosoftware/invenio-app-rdm/pull/568
closes #581 
**screenshots**
=> bugfix: onhover navbar item

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/licenses.html
=> landingpage: fix license fields

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/filters.py, invenio_app_rdm/records_ui/views/records.py, tests/api/test_record_api.py, tests/conftest.py
closes #579 
some of the work is already done, but there's still some issues...
=> details: start re-implementing the file preview and download

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/filters.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/recordManagement.js, setup.py
* Show manage section only if user has `update_draft` permission
Partially closes https://github.com/inveniosoftware/invenio-app-rdm/issues/595
=> landing-page: add permissions to record view

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less
=> style: protection widget

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less
=> style: license description inline with Readmore

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/list.overrides
=> deposit: fix styling in user records search

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
=> deposit: show message for metadata-only record

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/recordManagement.js
removes ```New version``` button.
=> landingpage- removes new version btn

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/licenses.html
=> bugfix: show each license in new line

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js
* removing pointer cursor- from title and surrounding.
* adding back the edit button.
=> uploads: remove cursor, add edit button

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search_deposit.html
=> sort: adds sort options to uploads/search

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
=> user-records-search: fix status icon alignment

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/export.html
This should fix the btn issue on export template.
=> style: export template btn

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
related to #596 
requires https://github.com/inveniosoftware/react-invenio-forms/pull/63 and https://github.com/inveniosoftware/react-invenio-deposit/pull/234
=> deposit: disable unwanted CKEditor plugins from the DescriptionsField

invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py
* Fixes an issue where the edit button was shown to users who did
not have permission to access the record.
=> records: ensure edit button is only show for owner

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/651
=> uploads: make result buttons compact

invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py
- requires: https://github.com/inveniosoftware/invenio-records-resources/pull/208
- closes #650
=> permissions: have RecordItem project needed ones

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search_deposit.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/649
requires https://github.com/inveniosoftware/invenio-rdm-records/pull/433
requires https://github.com/inveniosoftware/invenio-records-resources/pull/209/files
=> wip split uploads search record statuses

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
=> landing_page: fix Upload information typo

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
- :warning: It doesn't do anything yet
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/437
**Toggle off in record search**
**Toggle on in uploads search**
=> searches: re-enable version switch

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/deposits.py, setup.py
closes inveniosoftware/invenio-db#145
=> config: set default connection pool pre ping

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/version.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/686
=> landing-page: versions list

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js, setup.py
closes inveniosoftware/invenio-app-rdm#707
=> landing-page: redirect to record latest version

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search_deposit.html, setup.py
- requires https://github.com/inveniosoftware/invenio-rdm-records/pull/449 i.e. rdm-records 0.28.9
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/440
=> 440 sort by versions

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/701
requires https://github.com/inveniosoftware/invenio-rdm-records/pull/467
=> UI serialization version

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
requires https://github.com/inveniosoftware/invenio-rdm-records/pull/473
=> landing-page: use `version` sort option for versions

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/725
=> detail: use latest_html record link

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/735
result:
=> landing-page: change caption in the preview box on file change

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/records_ui/views/filters.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/734
result:
=> landing-page: preview files with uppercase file extensions

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
=> ui: fix overlapping btn in upload list

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/search.less
=> ux: fix long names in facets breaking layout

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/export.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less
* Adds draft preview
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/669
=> deposit: draft preview

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/frontpage.html
Updated the links in the frontpage.
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/759
=> Changing links in frontpage (issue #759

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
* adds PIDs and identifiers fields to the deposit form
* closes #766
=> deposit: add identifiers fields

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/doi.html, invenio_app_rdm/records_ui/views/filters.py
Closes #760 
Update: DOI title added before the DOI badge.
=> records-ui: Re-enable the DOI badge in the landing page

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/457
=> deposit: added styles for file import note

invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/webpack.py, setup.py, tests/api/test_protect_files_rest.py, tests/api/test_record_api.py, tests/conftest.py
- closes https://github.com/inveniosoftware/invenio-records-resources/issues/225 (in part)
- requires https://github.com/inveniosoftware/invenio-rdm-records/pull/515
=> files: enable files in body of new record

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/440
=> search: Add custom request serialiser in searchApi config

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/deposit.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search_deposit.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.en.html
=> Add page titles

invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js
* Fixes large delete button.
* Fixes link to the record.
* Catch an unhandled error.
=> theme: ux fixes

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareModal.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.overrides
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/538
=> shareModal: Fix dropdown alignment

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareButton.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/537
=> shareButton: Fix alignment

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less
Fixes #257 
https://github.com/inveniosoftware/invenio-app-rdm/issues/257
=> Changed gradient color of navbar

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/views/filters.py
=> default_preview: fix display default_preview

invenio_app_rdm/upgrade_scripts/migrate_1_0_records_to_2_0.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/744
=> migration script: Fix version bug

invenio_app_rdm/config.py, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/navbar.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_login.html, invenio_app_rdm/theme/views.py
Closes https://github.com/inveniosoftware/invenio-communities/issues/229.
=> views: add quick-create (plus) menu

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
* add doi in the ui in the versions section
=> Add doi in versions

invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
Blocked by release of https://github.com/inveniosoftware/react-invenio-deposit/pull/273
=> deposit: inject PIDs field config

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py
requires https://github.com/inveniosoftware/invenio-rdm-records/pull/565
Move endpoint from RDM-Records
=> views: add pid resolving redirection ui endpoint

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/navbar.less
closes https://github.com/inveniosoftware/invenio-communities/issues/292
=> header: fix onhover in even menu items

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/811
=> DOI: fix new line break for long DOIs 

invenio_app_rdm/upgrade_scripts/migrate_2_0_to_3_0.py
Script to upgrade from InvenioRDM 2.0 to 3.0
Everything seemed to work fine after following the new upgrade instruction (PR in docs pending). (See comment in line for only note).
=> upgrade: provide upgrade script from 2.0 to 3.0

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/doi.html
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/816
=> landing page: doi modal text 

invenio_app_rdm/upgrade_scripts/fix_migrated_records_from_1_0_to_2_0.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/744
=> upgrade: Adds script to fix upgrade version issue

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/navbar.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
=> theme: fix search field hover

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareModal.js
=> share-link: Fix preview link

invenio_app_rdm/config.py
=> config: disable communities by default

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
Long DOIs now in one line
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/811
=> Line break for long DOIs

invenio_app_rdm/config.py
replaces https://github.com/inveniosoftware/invenio-app-rdm/pull/808
requires https://github.com/inveniosoftware/invenio-rdm-records/pull/589
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/812
=> landing page: add datacite json export

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.de.html
=> searchguide: adds german language template

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.de.html
Based on the comments that I made [here](https://github.com/tu-graz-library/invenio-config-tugraz/pull/61/files) (unfortunately after the PR was already merged), I propose these fixes and improvements to the German help-search translation.
=> Fix German help-search translation

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search_deposit.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/filters.py, setup.py
=> search: align to new facets structure and remove dereferencing

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js, invenio_app_rdm/theme/webpack.py, setup.py, tests/api/test_protect_files_rest.py, tests/api/test_record_api.py, tests/conftest.py, tests/ui/test_deposits.py
- depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/596 being released
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/840
=> resource_type: integrate changes due to transition to vocabulary

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html
=> link creator's name with search 

invenio_app_rdm/upgrade_scripts/migrate_3_0_to_4_0.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/854
=> upgrade: upgrade script from 3.0 to 4.0

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less
=> landing page: fix box corners

invenio_app_rdm/config.py
=> config: add iiif image handler and decorator

invenio_app_rdm/translations/messages.pot
=> i18n: extracted marked strings for translation

invenio_app_rdm/config.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/400
=> celery: update expired embargos

invenio_app_rdm/config.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/892
* needs https://github.com/inveniosoftware/invenio-rdm-records/pull/654
=> export: adds csl json

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/subjects.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search_deposit.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js
* partially closes https://github.com/inveniosoftware/invenio-rdm-records/issues/631
* needs https://github.com/inveniosoftware/react-invenio-deposit/pull/303
=> vocabulary: add subjects

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/export.html
close #906 
https://user-images.githubusercontent.com/6756943/122191571-274ffd00-ce93-11eb-9b8f-9b193f629cd8.mov
=> preview: add back to form button

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/citation.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/867
* needs https://github.com/inveniosoftware/invenio-rdm-records/pull/648
https://user-images.githubusercontent.com/15194802/121540329-b0d07c80-ca06-11eb-8503-b94f26454d2e.mp4
=> Citations generation: Config and React app

invenio_app_rdm/config.py
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/683
=> config: datacite xml serializer added

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
* Updates landing page to display languages
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/691
* [EDIT] closes https://github.com/inveniosoftware/invenio-rdm-records/issues/632
=> additional titles: adds title type and language vocabularies

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/contributors.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/670
* needs https://github.com/inveniosoftware/invenio-app-rdm/pull/920 (for tests)
=> vocab: adds role vocab to form config

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/696 
* needs https://github.com/inveniosoftware/invenio-rdm-records/pull/698
* [EDIT[ also closes https://github.com/inveniosoftware/invenio-app-rdm/issues/781
* [EDIT] also closes https://github.com/inveniosoftware/invenio-rdm-records/issues/633
* [EDIT[ also closes https://github.com/inveniosoftware/invenio-rdm-records/issues/634 (at least in part)
=> additional descriptions: adds type and language vocabularies

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/700
=> vocab: update date type to use vocabulary

invenio_app_rdm/records_ui/views/deposits.py
* requires https://github.com/inveniosoftware/invenio-rdm-records/pull/704
=> vocabulary: rename titletype vocab

invenio_app_rdm/theme/webpack.py
depends on https://github.com/inveniosoftware/react-invenio-deposit/pull/322
=> translations: add UI i18n deps

invenio_app_rdm/records_ui/views/deposits.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/709
=> views: use proper locale negotiation

invenio_app_rdm/records_ui/views/deposits.py, setup.py, tests/conftest.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/705 
* needs https://github.com/inveniosoftware/invenio-rdm-records/pull/711
=> vocabulary: rename to resourcetype

invenio_app_rdm/config.py
=> config: rename datacite export formats

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/tombstone.html, invenio_app_rdm/translations/messages.pot
=> i18n: mark & extract missing strings

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/citation.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utlis/CopyButton.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/button.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/list.overrides, invenio_app_rdm/theme/webpack.py, setup.py
closes #901 
[EDIT] closes https://github.com/inveniosoftware/invenio-app-rdm/issues/914
Added separators between export methods
=> ux: change styling for exports tab on the landing page

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/943
=> landing page: fix multiple styles selected on citation box

invenio_app_rdm/config.py, run-tests.sh, setup.py, tests/conftest.py, tests/ui/conftest.py, tests/ui/test_export_formats.py
closes #905
depends on inveniosoftware/invenio-rdm-records#663
=> export: add dublin core xml

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/frontpage.html
=> frontpage: Fix broken links

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/licenses.html, invenio_app_rdm/records_ui/views/deposits.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/718
=> landing page: update licenses to use UIObject

invenio_app_rdm/theme/webpack.py
- This bumps yup across major versions, but no problems
were detected so far. More testing of the js pages will
be valuable.
- part of closing https://github.com/inveniosoftware/invenio-app-rdm/issues/956
=> js-dependencies: bump yup for security

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/subjects.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/269
=> landing-page: format subjects

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/966 in part
=> deposit: style additional descriptions labels

invenio_app_rdm/config.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareModal.js, invenio_app_rdm/theme/assets/semantic-ui/translations/invenio_app_rdm/i18next.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/994
=> config: change citation styles order

invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/992
requires https://github.com/inveniosoftware/react-invenio-deposit/pull/360
supersedes https://github.com/inveniosoftware/react-invenio-deposit/pull/357
=> pids: configure record pid label from config

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/subjects.html
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/982
=> landing page: show keywords tag only once

invenio_app_rdm/records_ui/views/deposits.py, tests/ui/test_deposits.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/760
* needs https://github.com/inveniosoftware/invenio-vocabularies/pull/77
=> resource_type: update dumping

invenio_app_rdm/config.py
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/900
=> config: fix iiif template preview path

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/895
=> uploads: make creator name optional

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.variables
=> theme: display more items per dropdown

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/filters.py, tests/ui/test_filters.py
=> detail: show alternate identifiers [+]

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/filters.py, invenio_app_rdm/records_ui/views/records.py
- pre-req: https://github.com/inveniosoftware/invenio-previewer/pull/149
- closes #767
=> preview: add .txt file preview + refactor

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
=> landing page: update citation section styling

invenio_app_rdm/upgrade_scripts/migrate_4_0_to_6_0.py
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/926
=> upgrade: script record upgrade from v4 to v5

invenio_app_rdm/config.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/EditButton.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js, tests/conftest.py
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/778
Fixes the following actions:
- From the landing page:
- Edit button
- Inside the share modal: create link and delete link
- In the user search page (deposit search)
- Delete a draft
- Edit a record
=> config: enable csrf checks

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/subjects.html
=> landing page: Fix subjects display error

invenio_app_rdm/upgrade_scripts/migrate_4_0_to_6_0.py, invenio_app_rdm/version.py
mere cherry pick of maint-6.x commits
=> Fix master

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/contributors.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/creators.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/304
https://user-images.githubusercontent.com/15194802/129589993-a9b9b16f-ada7-4e3b-845e-b51ddd4d195b.mp4
=> landing page: Fix affiliations display

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/index.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/569
=> components: Overrides error cmp

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.en.html
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/886
=> search: extends template from config

invenio_app_rdm/records_ui/views/records.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1051
=> deposit: fix related identifiers preview bug

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/645
=> files preview: truncate file names

invenio_app_rdm/config.py
* closes https://github.com/inveniosoftware/invenio-drafts-resources/issues/158
=> celery: Update cleanup_drafts task

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/contributors.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/creators.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/index.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.en.html, invenio_app_rdm/version.py, setup.py
- landing page: Fix affiliations display
- components: Overrides error cmp
- search: extends template from config
- view: only preview if valid draft
- files preview: truncate file names
- celery: Update cleanup_drafts task
- dependencies: bump invenio-rdm-records
- release: v6.0.3
=> cherry pick 6.0.3

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less, invenio_app_rdm/version.py
- style: fix landing page less typo
- release: v6.0.4
=> landing page less fix2

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less, invenio_app_rdm/version.py
- style: fix landing page less typo
- release: v6.0.4
=> cherry pick 6.0.4

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/799
=> landing page: Fix subjects display

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
Reverts inveniosoftware/invenio-app-rdm#1100
:tired_face: Just to point at right places
=> Revert "landing page: Fix subjects display"

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/160
=> theme: remove unusd css class .btn-primary

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less
=> landing page: fix styling for file preview and file list box

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
- This is just a re-targeted version of #1100 i.e. it's good to go when we settle on merge strategy
- landing page: Fix subjects display
=> fix subjects display2

invenio_app_rdm/config.py
=> config: add task for deletion of ips

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_frontpage.html
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1117
=> ARIA labels for search buttons

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html
- alt tags for **img**
-  aria-labels for **a**
- title for **a**
=> A11y: ORCID and ROR icons on item pages

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils/CopyButton.js
Accessible label with translation option
=> A11y- ARIA label and translation for copy button

invenio_app_rdm/records_ui/views/deposits.py
closes inveniosoftware/invenio-rdm-records#855
=> views: fix initial record data

invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/version.py, setup.py, tests/ui/conftest.py
- services: order methods to pass identity first
- release: v8.0.0.dev2
=> 258 bump records resources for method parameters order

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js
https://dequeuniversity.com/rules/axe/4.3/aria-input-field-name
=> A11y: Citation style listbox: ARIA input fields must have an accessible name

invenio_app_rdm/config.py, setup.py
- requires https://github.com/inveniosoftware/invenio-rdm-records/pull/832
- closes #1169 
**Config**
```shell
$ invenio shell
In [2]: current_app.config["VOCABULARIES_DATASTREAM_READERS"]
Out[2]:
{'orcid-http': invenio_vocabularies.contrib.names.datastreams.OrcidHTTPReader,
'tar': invenio_vocabularies.datastreams.readers.TarReader,
'yaml': invenio_vocabularies.datastreams.readers.YamlReader}
In [3]: current_app.config["VOCABULARIES_DATASTREAM_TRANSFORMERS"]
Out[3]: {'xml': invenio_vocabularies.datastreams.transformers.XMLTransformer, 
'orcid-xml': invenio_vocabularies.contrib.names.datastreams.OrcidXMLTransformer}
In [4]: current_app.config["VOCABULARIES_DATASTREAM_WRITERS"]
Out[4]:
{'names-service': invenio_vocabularies.contrib.names.datastreams.NamesServiceWriter,
'service': …
```
=> config: add vocabulary datastreams

invenio_app_rdm/records_ui/views/__init__.py
- fixes issue reported by @max-moser about current_app not available in blueprint registering context
=> views: fix pid provider scheme extraction

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/deposits.py, tests/ui/test_deposits.py
=> dashboard: whitelist allowed routes

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js
closes #1150 
sets the trigger to the whole title
=> fix: update accordion trigger

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/searchapp.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/dashboard.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/communities.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/uploads.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, tests/ui/test_deposits.py
=> dashboard: add communities tab

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/index.js
=> dashboard: add url deep linking

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/searchapp.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/dashboard.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/requests.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/search.less
* closes #1181
* Needs https://github.com/inveniosoftware/invenio-requests/pull/127
* Needs https://github.com/inveniosoftware/react-searchkit/pull/214
* Needs https://github.com/inveniosoftware/invenio-theme/pull/254
=> [Depends on react-searchkit/pull/214 and invenio-requests/pull/127]Add request tab

invenio_app_rdm/config.py
This PR is needed for the OAI-PMH sets integration
=> config: add default indexer index

invenio_app_rdm/records_ui/searchapp.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1214
**Note for reviewers:** Only check second commit https://github.com/inveniosoftware/invenio-app-rdm/pull/1220/commits/268fcb4473ecae38b84fd581b5e9b0316a472bfb
=> [NEEDS https://github.com/inveniosoftware/invenio-app-rdm/pull/1212]Add initial filters

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/requests.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1217
* Needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1212 
**Note for reviewers:** Only check second commit https://github.com/inveniosoftware/invenio-app-rdm/pull/1221/commits/31b8240cc7de6fe8b14a9e669db6287236c4fead
=> [NEEDS https://github.com/inveniosoftware/invenio-app-rdm/pull/1212]Fix filters bug

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/searchapp.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/885
=> searchapp: add communities search config

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/requests.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1229
* needs https://github.com/inveniosoftware/react-searchkit/pull/217
=> [DEPENDS on https://github.com/inveniosoftware/react-searchkit/pull/217] requests: add empty pages

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/requests.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/search.less
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1238
=> requests: fix Open/Closed bug on page reload

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/deposit.html, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/index.js
closes #1249 
needs https://github.com/inveniosoftware/react-invenio-deposit/pull/417
=> deposit: pass community when creating a new record

invenio_app_rdm/config.py
Requires https://github.com/inveniosoftware/invenio-rdm-records/pull/888
Replaces https://github.com/inveniosoftware/invenio-oaiserver/pull/213
=> oai: add datacite and oai_datacite config

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
=> landing page: include version number in translation string

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js
=> landing page: prevent arrow icon from disappearing on preview

invenio_app_rdm/records_ui/views/deposits.py
When editing a deposit, if there is a review request and the receiver is a community then we resolve it. We inject also the community as a separate entity so that the UI can initialize the user's choice aligned with the backend information.
=> deposit: resolve community from an inclusion request when editing

invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html, invenio_app_rdm/theme/views.py
closes: inveniosoftware/invenio-app-rdm#1255
=> Navbar: link my requests to navbar

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/dashboard.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/communities.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1284
=> placeholder: replace with square-placeholder

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/navbar.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1257
=> navbar: Fix hovering

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/index.js, invenio_app_rdm/theme/assets/semantic-ui/translations/invenio_app_rdm/messages/en/translations.json
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1182
=> Dashboard: Tabs with i18n

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/index.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1254
=> landingPage: fix version facet display

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/manage_menu.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/records_ui/views/utils.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/EditButton.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareButton.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/message.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1247
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1272
* needs https://github.com/inveniosoftware/react-invenio-deposit/pull/418
=>  Add community header

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html
=> landing page: hide additional details if no content

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
=> landing page: prevent all-versions link from opening new tab

invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/requests_ui/views/requests.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1297
* needs https://github.com/inveniosoftware/invenio-drafts-resources/pull/183
Removes access to private variables in the views
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
By using GitHub, you have already agreed to the …
=> [DEPENDS ON invenio-drafts-resources/pull/183] views: remove access to private variable

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page/sidebar.less
=> landing page: align sidebar with article content

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/index.js
closes #1310 
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
=> dashboard: fix 404 when reload page

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/navbar.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/segment.overrides, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
* closes: inveniosoftware/invenio-app-rdm#1253
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions- …
=> ui: fix header element alignment

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/navbar.less, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
=> Header username

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/communities.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides, invenio_app_rdm/theme/templates/semantic-ui/invenio_requests/community-submission/index.html
Truncate request details contributors to 2 lines
closes: https://github.com/inveniosoftware/invenio-communities/issues/401
closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/1280
=> Community view: truncate community description to 2 lines

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js
Small refactor of the relative date in the requests
=> Dashboard requests: internationalization of relative date

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/deposit.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/index.js
Requires https://github.com/inveniosoftware/react-invenio-deposit/issues/428
=> communities: inject preselected community

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
1. …
=> RDMRecordFacetsValues: make whole facet clickable, including item count

invenio_app_rdm/records_ui/searchapp.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/dashboard.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html, invenio_app_rdm/version.py
* move reusable functions to
invenio-search-ui
* requires https://github.com/inveniosoftware/invenio-search-ui/pull/131
Co-authored-by: Pablo pineirin@gmail.com
=> searchapp: move reusable functions

invenio_app_rdm/config.py, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
- added query params variable to inject into react
closes https://github.com/inveniosoftware/invenio-requests/issues/129
=> requests: inject default query param

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides
* closes https://github.com/inveniosoftware/invenio-communities/issues/458
* closes https://github.com/inveniosoftware/invenio-communities/issues/456
=> members: add css rules

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/dashboard.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/segment.overrides
Remove communities enabled flag in dashboard.
Replace class use for classname.
closes: inveniosoftware/invenio-app-rdm#1337
=> Dashboard: use semantic ui menu instead of tab panes

invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/card.overrides
needs https://github.com/inveniosoftware/react-invenio-deposit/pull/463
=> deposit: add status box

setup.cfg
=> i18n: compile fuzzy strings

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/modal.overrides
* add modal actions style when wrapped in another component
=> theme: add modal actions styling

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/export.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ExportDropdown.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js
Closes [#1401](https://github.com/inveniosoftware/invenio-app-rdm/issues/1401)
- Changed the export-section to React because of accessibility issues with the jQuery version.
- Adjusted column widths and spacing to make sure the export section is scaling correctly on smaller screens.
=> landing page: improve a11y and responsiveness of export section

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
Closes [#445](https://github.com/inveniosoftware/react-invenio-deposit/issues/445)
- Stacked sidebar for tablet and mobile.
__Tablet__
__Mobile__
=> deposit form: add responsive layout

invenio_app_rdm/__init__.py, setup.cfg
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.
=> installation: bump invenio-rdm-records

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/feed.overrides
closes https://github.com/inveniosoftware/invenio-requests/issues/171
=> theme: add request-events styling

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides
Closes #1439
**Mobile/tablet version with manage options**
**Desktop version with manage options**
=> landing page: align main content and sidebar

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/frontpage.html
=> frontpage: make page responsive

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
=> search facets: hide clear btn when no selection

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.de.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.en.html
Closes [#1432](https://github.com/inveniosoftware/invenio-app-rdm/issues/1432)
=> search guide: add space between site header and main content

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_login.html
Closes #1409 and #1426 
Please let me know if you disagree with the design/layout, and if there are any possible/hidden cases I have not considered!
=> global menu: redesign burger menu

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
=> header: remove breadcrumbs

invenio_app_rdm/config.py, setup.cfg
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.
=> global: enable new user profiles

invenio_app_rdm/records_ui/views/__init__.py
=> remove pushed app context for config access

invenio_app_rdm/config.py, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/requests_ui/views/ui.py, invenio_app_rdm/theme/templates/semantic-ui/invenio_requests/community-invitation/index.html
closes https://github.com/inveniosoftware/invenio-requests/issues/186
closes https://github.com/inveniosoftware/invenio-requests/issues/184
=> request views: reroute request views to general view

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/button.overrides
Closes https://github.com/inveniosoftware/react-invenio-deposit/issues/470
Related to https://github.com/inveniosoftware/react-invenio-deposit/pull/473
=> Add transparent option for button

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/creatibutors.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/accordion.overrides
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1456
Fixed styling and alignment + a11y issues.
=> affiliations: fix styling and alignment

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/form.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/label.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/accordion.overrides
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1452
Related to PR https://github.com/inveniosoftware/react-invenio-deposit/pull/472
=> deposit form: layout improvements

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/feed.overrides
* refactor RequestsFeeds styling
=> requests: simplify the components styling

invenio_app_rdm/communities_ui/views/ui.py
closes: inveniosoftware/invenio-communities#408
=> Communities menu: use flask menu to generate communities menu

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/dashboard.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/index.js
* closes: inveniosoftware/invenio-app-rdm#1473
=> Dashboard: add user full name and avatar.

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/uploads.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables
closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/1478
=> my dashboard: show record status in uploads list

invenio_app_rdm/communities_ui/views/communities.py, invenio_app_rdm/requests_ui/views/requests.py
closes https://github.com/inveniosoftware/invenio-communities/issues/500
=> Communities relations

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/requests.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1495
=> my dashboard requests: adjust layout for mobile and tablet

invenio_app_rdm/communities_ui/templates/semantic-ui/invenio_communities/details/index.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/base.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/image.overrides
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/482
**Reminder**
2. You agree …
=> theme: add css classes for placeholder image

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/table.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/button.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.overrides
Closes https://github.com/inveniosoftware/invenio-communities/issues/564
Needs https://github.com/inveniosoftware/invenio-communities/pull/578
=> community members: add responsive styling

invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html
=> request: align community request title with actions

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
Closes https://github.com/inveniosoftware/react-invenio-deposit/issues/471
Added `includesPaths`-prop to all  `AccordionField`.
Needs PR https://github.com/inveniosoftware/react-invenio-forms/pull/131
=> deposit: add includesPaths prop to AccordionField

invenio_app_rdm/communities_ui/views/communities.py, invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/requests_ui/views/ui.py
requires: https://github.com/inveniosoftware/invenio-communities/pull/583
=> communities: fix uuid field

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/modal.overrides
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1483
https://user-images.githubusercontent.com/21052053/167440259-5da7b6c7-a832-48d5-81b3-fafbf2d06397.mov
=> modal: add workaround for invisible modal loader

invenio_app_rdm/communities_ui/views/communities.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/manage_menu.html, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1520
=> preview: show/hide management box on different scenarios

invenio_app_rdm/communities_ui/views/communities.py, invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/records_ui/views/utils.py, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-invitation/community_dashboard.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-invitation/user_dashboard.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/requests_ui/views/ui.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities.js, invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/base.html, invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html, invenio_app_rdm/users_ui/views/dashboard.py, setup.cfg
* requires: https://github.com/inveniosoftware/invenio-communities/pull/626
* partially address: https://github.com/inveniosoftware/invenio-app-rdm/issues/1218
=> requests: refactor views

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
- requires https://github.com/inveniosoftware/invenio-rdm-records/pull/936
https://user-images.githubusercontent.com/6756943/167415201-4a87fef7-19bc-47e1-a745-bc8936d26b5b.mov
review requested to @jennur and @kpsherva for UI/UX, if there are tiny issues maybe they can be addressed separately to allow this feature going into the release
=> Funding integration

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides
Needed for: https://github.com/inveniosoftware/invenio-communities/pull/634
=> Css: add rule for current user in community members

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities.js
=> communities: keep aspect ratio of list results images

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities.js, invenio_app_rdm/users_ui/searchapp.py
requires https://github.com/inveniosoftware/invenio-requests/pull/212
=> User requests

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js
Adds all profile Icons to creators in search. Previously only the first was shown. Closes #1492.
(Also fixed spacing)
**Reminder** …
=> Add all possible profile icons for creators in search

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/card.overrides
**Needs PR** https://github.com/inveniosoftware/invenio-communities/pull/641 <<-- Screenshots available
=> community cards: make images same size

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/requests_ui/views/requests.py
* The template has empty files passed to it when we use
it for the request details page
**Reminder**
1. You license your contribution under the same …
=> files: fix details template when empty files are passed

invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html
=> record request: fix label styling bug

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
=> community header: make logo size mini

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/requests_ui/views/requests.py
=> files: resolve for dashboard

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/views/records.py
=> detail: fix broken preview

babel.ini
**WithExtension** and **AutoEscapeExtension** are built-in now. see: [release note](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0)
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
=> babel: remove deprecated extensions.

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1584
before:
after:
=> record details: reduce whitespace community header

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/table.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/button.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.overrides
Fix mobile UI issues
closes: [inveniosoftware/invenio-app-rdm#661](https://github.com/inveniosoftware/invenio-communities/issues/661)
closes: https://github.com/inveniosoftware/invenio-communities/issues/646
depends on: https://github.com/inveniosoftware/invenio-communities/pull/671
=> Members: add responsive layout to tablet resolution [DEPENDS ON https://github.com/inveniosoftware/invenio-communities/pull/671]

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1604
=> my uploads: prevent overflow on long title

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/card.overrides
closes https://github.com/inveniosoftware/invenio-communities/issues/659
=> community frontpage: make community logos full width

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1583
needs https://github.com/inveniosoftware/invenio-communities/pull/676
=> community header: add reference and show community visibility

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/input.overrides
* Needed by https://github.com/inveniosoftware/invenio-communities/pull/670
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1570
=> css: add grid for invitation searchbar

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1586
https://user-images.githubusercontent.com/21052053/169292262-58433320-5e4c-48de-8b8d-8b1c73d60e73.mov
=> rdm-facet-container: preserve space for clear btn in header

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/image.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides, invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1585
please ignore the yellow button, I was testing overridability of variables :)
=> theme: fix webpack configuration of theming

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/segment.overrides
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1600
* needed by https://github.com/inveniosoftware/invenio-communities/pull/672
=> css: add min-height to invitation segment

invenio_app_rdm/__init__.py
=> release: v9.0.0.rc2

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/segment.overrides
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1600
=> css: update min-height for invitation modal

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/feed.overrides
* closes https://github.com/inveniosoftware/invenio-requests/issues/204
=> feed: remove max width

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/icon.overrides
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1581
@kpsherva @jennur I've applied the changes you suggested in https://github.com/inveniosoftware/invenio-app-rdm/pull/1519 and rebased on master.
=> CSS: standardize identity icon display

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js
Fixes request type labels  and facets in user dashboard, Community requests search 
needs https://github.com/inveniosoftware/invenio-requests/pull/231
needs https://github.com/inveniosoftware/invenio-communities/pull/685
=> request: add type labels

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1649
=> css: remove negative margin

invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-invitation/community_dashboard.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-invitation/user_dashboard.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/macros/request_header.html, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1596
needs https://github.com/inveniosoftware/invenio-theme/pull/288
creator change included here https://github.com/inveniosoftware/invenio-requests/pull/235
=> request details: add back button and use all white space

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides
* closes https://github.com/inveniosoftware/invenio-communities/issues/690
=> css: fix checkbox and avatar alignment

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/button.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.overrides, invenio_app_rdm/users_ui/views/dashboard.py
Fix mobile view.
Add status icon.
Add extra space for user full name.
closes: #1595
depends on: https://github.com/inveniosoftware/invenio-communities/pull/681
depends on: https://github.com/inveniosoftware/invenio-requests/pull/238
=> Invitations: fix tablet view [DEPENDENCIES]

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1215
https://user-images.githubusercontent.com/15194802/172560824-34461794-d2b8-4a97-ac28-db38d9c6e62b.mp4
=> dashboard: add request actions

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
In the deposit form, the contributor pop up dialogue was being erroneously populated with *creator* metadata. This caused the wrong roles to show where different contributor roles have been defined.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
=> Load correct metadata to contributor pop-up

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1715
=> mobile menu: add space to close button

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/form.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/card.overrides
* closes https://github.com/inveniosoftware/react-invenio-deposit/issues/519
=> card: access field custom styling

invenio_app_rdm/communities_ui/views/communities.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities.js, invenio_app_rdm/users_ui/searchapp.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1518
=> [NEEDS #invenio-communities/pull/704]searchapp: update response handler

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/feed.overrides, invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1738
Styling for https://github.com/inveniosoftware/invenio-requests/pull/253
=> feed: fix responsive bugs for avatars

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/table.overrides
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1735
=> upload: fixed files list styling on mobile

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests_items/ComputerTabletRequestsItems.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests_items/MobileRequestsItems.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides
closes: https://github.com/inveniosoftware/invenio-communities/issues/702
Desktop:
Tablet:
Mobile:
=> Requests: re-design requests list view

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/label.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
closes https://github.com/inveniosoftware/invenio-communities/issues/732
=> communities: added restricted label to community header and list.

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/message.overrides
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1774
- The css-reference was outdated, updated to new id-name
=> message overrides: update id-reference in css

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1616
- Adds `onerror` logic to function
=> detail: add image onerror inline js to script

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/previewer/__init__.py, invenio_app_rdm/records_ui/previewer/iiif_simple.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/iiif_preview.html, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/previewer/iiif_simple.less, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/webpack.py, setup.cfg
Provides preview of attached images using IIIF. WIP but would appreciate a quick review. 
Note that GIFs won't currently work, which I'm investigating here: https://github.com/inveniosoftware/flask-iiif/issues/91
Closes #1708
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions …
=> Landing Page: Simple IIIF previewer for images

invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/filters.py
Depends on #1709
Adds a has_images Jinja filter, for local customization / possible future use.
Depends #1709
**Reminder**
1. You license your contribution under the same terms as the current …
=> UI Filters: add has_images filter

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
=> landing page: fix image placeholder bug

setup.cfg
=> setup: upper pin werkzeug

setup.cfg
This reverts commit f57b98d35732e6be2843752f9f1b8132894bd174.
Upper pin was moved to invenio-base
**Reminder**
1. You license your contribution under …
=> Revert "setup: upper pin werkzeug"

invenio_app_rdm/theme/webpack.py
With this PR it is possible to import Javascript classes into other packages. 
**Reminder**
2. You agree …
=> add js/invenio_app_rdm alias

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
Now explicitly adds the fieldPath prop to field components to move away from relying on defaultProps values.
related to https://github.com/inveniosoftware/react-invenio-deposit/pull/551
=> deposit form: add fieldPath prop to field components

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/base.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js
=> Dashboard: fix mobile pagination [DEPENDS ON https://github.com/inveniosoftware/invenio-search-ui/pull/150]

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/base.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1697
- Adds spacing to sort-label
- Adds `.capitalize` class as needed in https://github.com/inveniosoftware/invenio-communities/pull/772
=> sort dropdowns: add spacing to label

invenio_app_rdm/records_ui/views/deposits.py
Refs: https://github.com/inveniosoftware/invenio-app-rdm/issues/1707
=> global: Fixes wording of help-text.

invenio_app_rdm/records_ui/views/deposits.py
=> config: convert dict to list

invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/custom_fields/utils.js
=> ui: wrap ui properties in props field

invenio_app_rdm/records_ui/views/deposits.py
=> cf: pass g.identity to vocabulary options method

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/card.overrides
Closes https://github.com/inveniosoftware/react-invenio-deposit/issues/561
- Fixes some spacing inconsistencies.
Related to https://github.com/inveniosoftware/react-invenio-deposit/pull/570
=> access-right card: update inconsistent spacing

invenio_app_rdm/config.py
* closes #1841
* depends on https://github.com/inveniosoftware/invenio-requests/pull/274
**To be tested!!!**
=> requests: add cron to check for expired requests

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareModal.js
=> search: refactor styling

invenio_app_rdm/__init__.py
=> release: v10.0.0.dev1

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/records.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1845
=> Add custom fields landing page

invenio_app_rdm/config.py, setup.cfg
- requires https://github.com/inveniosoftware/invenio-rdm-records/pull/1042
- requires https://github.com/inveniosoftware/invenio-communities/pull/795
- closes https://github.com/inveniosoftware/invenio-communities/issues/794
=> config: set communities namespaces to rdm namespaces

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
* closes: [inveniosoftware/invenio-administration#56](https://github.com/inveniosoftware/invenio-administration/issues/43)
=> Facets: move facets to invenio-search-ui REQUIRES[nvenio-search-ui#162 invenio-theme#313]

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_login.html
* closes: inveniosoftware/invenio-administration#66
Admin:
Not admin:
=> Administration: add admin link in the profile menu

invenio_app_rdm/upgrade_scripts/migrate_9_0_to_10_0.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1037
=> migration: add script to migrate to v10

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1890
Adds Helvetica font to rdm-theme
=> theme: specify helvetica font

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html
=> detail: rename custom field template context vars

invenio_app_rdm/__init__.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/requests_ui/views/requests.py
=> V10.0.0.dev12

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/deposits.py
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1204
- depends on: https://github.com/inveniosoftware/react-invenio-deposit/pull/568 .
- Goes about it by just adding extra content to the modal. Seems like the simplest.
**Example Screenshot**
In the community review
Serviceable.
=> Allow customization of publish modal

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/header.overrides
Related to https://github.com/zenodo/zenodo-rdm/pull/59
=> theme: specify muted color for muted header

MANIFEST.in, invenio_app_rdm/cli.py, invenio_app_rdm/config.py, invenio_app_rdm/fixtures/__init__.py, invenio_app_rdm/fixtures/pages.py, invenio_app_rdm/fixtures/pages/.gitkeep, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/default_static_page.html, setup.cfg
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1934
=> staticPages: add static pages

MANIFEST.in, invenio_app_rdm/config.py, invenio_app_rdm/theme/static/robots.txt, invenio_app_rdm/theme/views.py, tests/ui/test_static.py
=> Robots: add robots.txt

invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/macros/request_header.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests_items/ComputerTabletRequestsItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests_items/MobileRequestsItem.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
Move action buttons to a dropdown.
closes: inveniosoftware/invenio-requests#264
=> Dashboard requests mobile: center content

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities_items/ComputerTabletCommunitiesItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities_items/MobileCommunitiesItem.js
closes: inveniosoftware/invenio-theme#335
=> Dashboard communities: add labelled icon

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/EditButton.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js
* closes: inveniosoftware/react-invenio-forms#168
=> Axios: Centralize imports

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities_items/ComputerTabletCommunitiesItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities_items/MobileCommunitiesItem.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
closes: zenodo/zenodo-rdm#48
Communities computer tablet search:
Communities mobile search:
Communities dashboard computer tablet:
Communities dashboard mobile:
=> Communities dashboard: add data to the search results

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
Closes https://github.com/inveniosoftware/invenio-theme/issues/301
=> detail: add has-placeholder class

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/frontpage/RecordsList.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/frontpage/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/frontpage/override.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/8
=> RecordsResultsListItem: refactor and add overridable

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/override.js
* closes https://github.com/zenodo/who-rdm/issues/4
* needs https://github.com/inveniosoftware/react-invenio-deposit/pull/601
=> deposit: overridable form

MANIFEST.in, invenio_app_rdm/cli.py, invenio_app_rdm/fixtures/__init__.py, invenio_app_rdm/fixtures/oai_sets.py, tests/fixtures/app_data/oai_sets.yaml, tests/fixtures/conftest.py, tests/fixtures/test_cli.py, tests/fixtures/test_fixtures.py
* add cli command for creating fixtures
* cover the fixture and cli with tests
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1931
=> add the feature mechanism to load oai sets

invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/users_ui/views/dashboard.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1987
=> expand: pass identity on links

invenio_app_rdm/__init__.py
=> release: v11.0.0.dev7

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/deposits.py
This PR parameterize deposit render templates for `create `and `edit` page. This will improve the overriding process,
see concrete issue description on [discord](https://discord.com/channels/692989811736182844/704625518552547329/1047339417322405918)
There are other templates hardcoded, please let me know if we should include them all in this PR.
**Reminder**
By using GitHub, you have …
=> deposit: parameterize templates

invenio_app_rdm/__init__.py
=> release: 11.0.0.dev8

invenio_app_rdm/__init__.py, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
=> V11.0.0.dev9

invenio_app_rdm/__init__.py, invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/records.py
* closes https://github.com/zenodo/zenodo-rdm/issues/126
=> records_ui: configurable record detail template

MANIFEST.in, invenio_app_rdm/config.py, invenio_app_rdm/tasks.py, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/files_integrity_report/email/files_integrity_report.html, invenio_app_rdm/utils/files.py, setup.cfg, tests/conftest.py, tests/mock_module/__init__.py, tests/mock_module/templates/mock_mail.html, tests/mock_module/views.py, tests/test_tasks.py
=> Migrated checksum and integrity report tasks

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
=> Overridable: refactor prop passing

invenio_app_rdm/__init__.py
=> release: v11.0.0.dev11

invenio_app_rdm/config.py
- closes https://github.com/inveniosoftware/helm-invenio/issues/58
=> config: set mail_default_sender

invenio_app_rdm/cli.py, invenio_app_rdm/fixtures/__init__.py, invenio_app_rdm/fixtures/pages.py, invenio_app_rdm/fixtures/pages/.gitkeep, setup.cfg, tests/fixtures/app_data/pages.yaml, tests/fixtures/app_data/pages/about.html, tests/fixtures/test_fixtures.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1989
=> Add static pages

invenio_app_rdm/config.py, invenio_app_rdm/utils/files.py, tests/test_tasks.py
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2002
=> config: re-order and remove unused

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/frontpage/RecordsList.js
Hide section on empty results.
closes: #1996
=> Records list: refactor override to use only jsx

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_login.html
Makes the header menu more navigable for screenreader users.  
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1907
=> Plus menu in header: add ARIA label

invenio_app_rdm/upgrade_scripts/migrate_10_0_to_11_0.py
- closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/447
=> upgrade scripts: version 10 to 11

invenio_app_rdm/__init__.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html
Depends on:
- https://github.com/inveniosoftware/invenio-rdm-records/pull/1158
- https://github.com/inveniosoftware/invenio-records-resources/pull/426
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2037
**Reminder** …
=> records-ui: add "Download all" button

invenio_app_rdm/fixtures/data/oai_sets.yaml, tests/fixtures/test_cli.py
=> fixtures: include OpenAIRE OAI sets by default

invenio_app_rdm/communities_ui/templates/semantic-ui/invenio_communities/details/index.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/frontpage/RecordsList.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/frontpage/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/frontpage/override.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/overridableRegistry/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/overridableRegistry/mapping.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/base.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/javascript.html, invenio_app_rdm/theme/webpack.py, invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/communities.html, invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/requests.html, invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/uploads.html, setup.cfg
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2018
=> overridableRegistry: add global mapping for overriden components

invenio_app_rdm/config.py
* added UI option for exporting to geojson
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1154
=> ui: geojson export option

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ExportDropdown.js
The export dropdown needs an accessible name. fixes #2053
**Reminder** …
=> [#2053] Add Aria To Export Dropdown

invenio_app_rdm/config.py
* added UI option for exporting to MARCXML
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1165
=> ui: MARCXML export option

invenio_app_rdm/config.py
* added UI for exporting to marcxml for oai
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1173
=> oai-pmh: UI export for marcxml

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html, setup.cfg
* add latest invenio-banners to the requirements
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2088
Preview:
=> header: add banner macro

invenio_app_rdm/records_ui/views/deposits.py
- requires https://github.com/inveniosoftware/invenio-communities/pull/897
- closes https://github.com/inveniosoftware/invenio-communities/issues/871
=> inject user communities memberships

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
=> overridable: wrap DepositFrom AccordionFields

invenio_app_rdm/records_ui/views/decorators.py
=> upload: fix new draft with preselected community

invenio_app_rdm/__init__.py
=> release: v12.0.0.dev1

CHANGES.rst, invenio_app_rdm/__init__.py, setup.cfg
=> Maint 10.x

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/metrics.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/stats.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/stats_popup.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/filters.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/theme.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/table.overrides, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/statistics.en.html, invenio_app_rdm/theme/views.py
Closes https://github.com/inveniosoftware/invenio-stats/issues/120
=> landing page: add statistics component

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1191
- Updated custom fields widget loading from multiple sources
=> deposit: added multiple CF widget loaders.

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/button.overrides
closes: inveniosoftware/invenio-pages#66
=> Style: move auto columns to invenio-theme

invenio_app_rdm/config.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1208
=> serializers: ui export for bibtex

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/stats.html
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2108
=> stats: display only unique views and downloads

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/communities.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-inclusion/index.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-invitation/community_dashboard.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-invitation/user_dashboard.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/macros/request_header.html, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests_items/ComputerTabletRequestsItem.js
* the request details page in the user dashboard and community pages did expect only a draft. It now renders also when the request is related to an already published record.
* closes #2060
- https://github.com/inveniosoftware/invenio-rdm-records/pull/1182
=> request: allow rendering published record

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests_items/MobileRequestsItem.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/image.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides
* closes https://github.com/inveniosoftware/invenio-communities/issues/912
=> assets: landing page communities interface bugfixes

invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/decorators.py
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1998
Depends on https://github.com/inveniosoftware/invenio-records-resources/pull/454
=> File download: Return 404 if file to download isn't found

invenio_app_rdm/config.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1202
=> ui: DCAT export option

invenio_app_rdm/config.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1234
=> OAI-PMH: UI export for DCAT-AP

invenio_app_rdm/config.py
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2149
=> config: overwrite communities service components

invenio_app_rdm/__init__.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/views/records.py, setup.cfg
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2063
=> resolve deleted communities

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/communities.html, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/communityRecordsSearch/CommunityRecordsSearchAppLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/communityRecordsSearch/CommunityRecordsSearchBarElement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/communityRecordsSearch/CommunityRecordsSingleSearchBarElement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagmentDropdown.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.overrides, run-js-linter.sh
* needs https://github.com/inveniosoftware/react-invenio-deposit/pull/631
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2076
=> Add communities modal

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/communities.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/details.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/export.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/keywords_subjects.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/licenses.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/versions.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js, invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py
=> Fix sidebar boxes

invenio_app_rdm/records_ui/searchapp.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/communities.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagementDropdown.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/PendingCommunitiesModal/PendingCommunitiesSearch.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesListModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesSearch.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitySubmission/RecordCommunitySubmissionModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js, setup.cfg
* Allow to filter record's communities in the community modal
* needs https://github.com/inveniosoftware/react-invenio-deposit/pull/635
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2076
=> landingPage: allow filter communities

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagementDropdown.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/PendingCommunitiesModal/PendingCommunitiesSearch.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesSearch.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitySubmission/RecordCommunitySubmissionModal.js
=> assets: fix display of community actions feedback

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/communityRecordsSearch/CommunityRecordsSearchAppLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/base.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/ComputerTabletUploadsItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/MobileUploadsItem.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2162
=> translations: fix string concatenation and pluralizaton

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesListModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesSearch.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesSearchItem.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2193
=> landing page: fix remove button in community management panel

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html
closes #1870
*Before*
*After*
(not same document but you get the idea)
Fixes long filename in the Files table. Uses same CSS rules from FileUploaderArea.js https://github.com/inveniosoftware/react-invenio-deposit/blob/master/src/lib/components/FileUploader/FileUploaderArea.js#L96
**Reminder** …
=> files: fix long filename in files table

invenio_app_rdm/config.py, setup.cfg
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1268
Chase the changes in https://github.com/inveniosoftware/invenio-rdm-records/pull/1269
=> Stats: Adapt config to the stats restructuring in rdm-records

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitySubmission/RecordCommunitySubmissionModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js, invenio_app_rdm/theme/webpack.py, setup.cfg
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1276
=> assets: move deposit components from react-invenio-deposit

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, setup.cfg
Changes references display on the record landing page
=> record: change references display

invenio_app_rdm/__init__.py, invenio_app_rdm/config.py, setup.cfg
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.
=> config: bump index mapping to v6.0.0

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RemoveFromCommunity/RemoveFromCommunityAction.js
Closes [issues: 201](https://github.com/inveniosoftware/react-invenio-forms/issues/201)
**Reminder**
2. …
=> assets: Fix modal err msg & visibility on remove

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities.js, invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/communities.html, invenio_app_rdm/users_ui/views/dashboard.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/55
Hide "New community" button if no permissions.
=> communities: add permission check to display create button

invenio_app_rdm/records_ui/views/deposits.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1293
=> deposit_form: fixed deleting draft not possible unless refresh

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/frontpage/RecordsList.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/macros/records_list.html
Closes https://github.com/inveniosoftware/invenio-communities/issues/964
Adds placeholder for the "Recent uploads" list, both in jinja template & React component.
https://github.com/inveniosoftware/invenio-app-rdm/assets/21052053/08f065e3-4423-433d-a099-fd40feabdb7c
=> records_list: add placeholder for frontpage records list

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/doi.html
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/57
=> doi: update target URL

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
closes https://github.com/zenodo/zenodo-rdm/issues/340
=> custom-fields: fix loading in deposit form

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev4

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/records.py
addresses https://github.com/zenodo/zenodo-rdm/issues/264
=> custom-fields: add config for hiding fields in upload/landing page

invenio_app_rdm/config.py
resolves https://github.com/inveniosoftware/invenio-rdm-records/issues/1179
depends on:
- https://github.com/inveniosoftware/invenio-users-resources/pull/78
- https://github.com/inveniosoftware/invenio-rdm-records/pull/990
set configuration values needed for `invenio-notification` integration.
**Reminder** …
=> config: set config values for notifiations

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/theme.less, setup.cfg
* upgrades the instance to webpack 5
* fix theme import path
=> global: upgrade to invenio-assets v3

invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html
- fixes the display of affiliations: the string "None" might be displayed when the affiliations value is set to None and not empty string.
=> user: fix affiliations display

invenio_app_rdm/config.py, invenio_app_rdm/users/schemas.py
closes #2250 
Moving user notifications schemas from config to own file. Also removes duplicated definition of a schema.
**Reminder** …
=> schemas: move user notifications schemas from config to own file

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/macros/records_list.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2268
=> frontpage: Replace recent uploads React version with jinja version

invenio_app_rdm/__init__.py, invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.variables
* closes https://github.com/zenodo/who-rdm/issues/71
=> deposit: allow to configure the default value for files enabled

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/export.html, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2253
* rest api testing curl: https://gist.github.com/kpsherva/76981dfe235c9e49704fa16415b58608
=> Extra files

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev10

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/ComputerTabletUploadsItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/MobileUploadsItem.js
Closes https://github.com/inveniosoftware/invenio-requests/issues/328
Aligns the label styling with the rest of the site, adding the `horizontal` prop and `size="small"`.
=> uploads item: align label styling with rest of site

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev11

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/accordion.overrides
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2281
=> ui: remove accordion icon rotation

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/stats.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2298
=> stats: wrap stats table in accordion

setup.cfg
=> setup: revert python_requires 3.8

invenio_app_rdm/config.py, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/macros/request_header.html
depends on https://github.com/inveniosoftware/invenio-communities/pull/967
closes https://github.com/inveniosoftware/invenio-communities/issues/889
Update notification builder config variable in order to send community member invitation notifications.
**Reminder** …
=> config: add community invitation notification builder

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev13

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev14

invenio_app_rdm/config.py
depends on https://github.com/inveniosoftware/invenio-requests/pull/322
Add comment request event notification builder to notification builders config.
**Reminder** …
=> config: add comment request event notification builder

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev15

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev16

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/doi.html
=> DOI: fix concept doi

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/base.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/image.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides, invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html, invenio_app_rdm/users_ui/views/ui.py
Closes https://github.com/zenodo/zenodo-rdm/issues/410, closes https://github.com/zenodo/rdm-project/issues/209
Needs PR https://github.com/inveniosoftware/invenio-communities/pull/993
- Aligns community search layout with main communities search page.
- Adds "new" buttons to header.
- Fixes alignment-bug for username with/without affiliation
- Prefixes all tabs with "My"
=> user dashboard: align community search page with main com search page

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessRequests/AccessRequestsTab.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1387
Note: only the last commit corresponds to the current task. Previous one will be squashed after merge of this https://github.com/inveniosoftware/invenio-app-rdm/pull/2326
Preview:
=> Implement access request link expiration setting

setup.cfg
=> setup: bump invenio-files-rest

setup.cfg
=> setup: bump invenio-userprofiles

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/deposit.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/index.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2259
screenshots in https://github.com/zenodo/zenodo-rdm/pull/426
=> deposit: lock record files conditionally

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev17

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py
=> media-files: add download view

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev18

invenio_app_rdm/__init__.py, invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/access-form.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/guest-access-request/index.html, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/requests_ui/views/ui.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksTab.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessRequests/AccessRequestsTab.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/ShareModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/overridableRegistry/mapping.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/AccessRequestExpiration.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/timeline/AccessRequestTimelineEdit.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/timeline/AccessRequestTimelineRead.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/timeline/overrides/TimelineFeedHeader.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/header.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/label.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/modal.overrides, setup.cfg
* add a box with edit the request payload secret link expiration date
* add a box with a read-only preview of this box (for after request is accepted)
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1395
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2302
Request receiver editable box view:
No editable box in the guest view:
Errors handler:
Empty value - valid -> link will never expire:
Request results: 
accepted -> read-only box view (visible both for request creator(guest user) and request receiver):
declined/expired/cancelled -> no read-only box:
=> access-request: update request payload with secret link expiration date

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_frontpage.html
A Javascript null type error is thrown on the main landing page because the `header-search-bar` element doesn't exist.
This PR simply wraps a conditional if around it.
Also adds an aria label to the search input box to make the page accessible. (see https://www.accessibilitychecker.org/audit/?website=https%3A%2F%2Finveniordm.web.cern.ch+&flag=ww) 
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms …
=> Prevent JS front page error, make front page accessible

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/tombstone.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/records.py
Requires https://github.com/inveniosoftware/invenio-rdm-records/pull/1428
=> Record deletion: Display tombstone page

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev23

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/tombstone.html
=> tombstone: update styling

invenio_app_rdm/cli.py, invenio_app_rdm/communities_ui/views/ui.py, invenio_app_rdm/config.py, invenio_app_rdm/fixtures/__init__.py, invenio_app_rdm/records_ui/utils.py, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/filters.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/requests_ui/views/ui.py, invenio_app_rdm/upgrade_scripts/fix_migrated_records_from_8_0_to_9_0.py, invenio_app_rdm/upgrade_scripts/migrate_10_0_to_11_0.py, invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py, invenio_app_rdm/upgrade_scripts/migrate_2_0_to_3_0.py, invenio_app_rdm/upgrade_scripts/migrate_4_0_to_6_0.py, invenio_app_rdm/upgrade_scripts/migrate_6_0_to_7_0.py, invenio_app_rdm/upgrade_scripts/migrate_8_0_to_9_0.py, invenio_app_rdm/upgrade_scripts/migrate_9_0_to_10_0.py, invenio_app_rdm/users_ui/views/__init__.py, invenio_app_rdm/users_ui/views/dashboard.py, invenio_app_rdm/users_ui/views/ui.py, invenio_app_rdm/utils/files.py
Fixing some linter issues reported by `ruff`.
After the fixes (ignoring E501, the line length complaint):
```
mmoser@mx ~/rdm/modules/invenio-app-rdm [mm/linter-fixes] $ ruff invenio_app_rdm --ignore E501
mmoser@mx ~/rdm/modules/invenio-app-rdm [mm/linter-fixes] $ 
```
=> Linter fixes

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev24

setup.cfg
=> installation: bump major upper pin for invenio-records

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev26

invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py
=> upgrade: modify upgrade from v11 to v12

invenio_app_rdm/config.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagementDropdown.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesListModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesSearch.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitySubmission/RecordCommunitySubmissionModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2384
=> communityModal: pass record as prop

invenio_app_rdm/config.py, setup.cfg
Closes https://github.com/zenodo/rdm-project/issues/197
**Reminder** …
=> Using papaparse for csv

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/searchbar.html
Closes https://github.com/inveniosoftware/invenio-search-ui/issues/180
=> search bar: add aria-label

invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/macros/request_header.html, invenio_app_rdm/requests_ui/views/requests.py
* closes https://github.com/zenodo/rdm-project/issues/243
=> requests: render request details page empty topic

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/deposits.py
=> deposit: pass record and user quota to form config

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev27

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/searchbar.html
* closes https://github.com/zenodo/who-rdm/issues/79
=> menu: fix mobile display

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev28

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/AccessRequestForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksTab.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessRequests/AccessRequestsTab.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsers/AccessUsers.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsers/UserAccessSearchResult.js
closes https://github.com/zenodo/rdm-project/issues/11
Screenshots:
=> landing: ui fixes for access request.

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev29

invenio_app_rdm/administration/records/__init__.py, invenio_app_rdm/administration/records/records.py, invenio_app_rdm/administration/templates/semantic-ui/invenio_app_rdm/administration/records/record-admin-search.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/SetQuotaAction.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/SetQuotaForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RecordResourceActions.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RemovalReasonsSelect.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RestoreConfirmation.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/TombstoneForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/api/api.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/api/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/api/routes.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/AdministrationSearchLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/RecordSearchLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/filters/DeletionStatusFilter.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/filters/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/userModeration/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/UserActions.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/api/api.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/search/SearchResultItemLayout.js, invenio_app_rdm/theme/webpack.py, setup.cfg, tests/ui/test_filters.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2408
=> UI: add record administration panel

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitySubmission/RecordCommunitySubmissionModal.js
* closes https://github.com/zenodo/rdm-project/issues/168
=> community submission: fix direct publish calculation

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev30

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev31

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js
=> landing page: fix closing of community modal

invenio_app_rdm/administration/records/records.py, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/TombstoneForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/form.overrides
* administration: add is_admin search param
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1494
=> administration: point records search to /records

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/PendingCommunitiesModal/PendingCommunityRequestItem.js
* closes https://github.com/zenodo/rdm-project/issues/171
=> landing_page: pass request link to pending communities

invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2443
closes https://github.com/zenodo/rdm-project/issues/259
=> preview: add parent doi information for unpublished drafts

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev34

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/external_resources.html, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2423
No changes in the UI.
=> external resources: update semantic html

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js
=> landing_page: increase displayed communities to 3

invenio_app_rdm/communities_ui/views/ui.py, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RecordResourceActions.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/api/api.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/search/SearchResultItemLayout.js
*closes https://github.com/inveniosoftware/invenio-communities/issues/1006
=> ui: add community tombstone error handler

invenio_app_rdm/config.py
closes https://github.com/zenodo/zenodo-rdm/issues/524
=> config: added default github release class for rdm.

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev36

invenio_app_rdm/config.py
closes https://github.com/inveniosoftware/invenio-requests/issues/339
depends on https://github.com/inveniosoftware/invenio-requests/pull/353
Use notification builders for request actions.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including …
=> config: use request action notification builder

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/UserActions.js
=> user-administration: rename reactivate to verify

invenio_app_rdm/communities_ui/searchapp.py, invenio_app_rdm/records_ui/searchapp.py, invenio_app_rdm/users_ui/searchapp.py
=> searchapp: reduce pagination options

invenio_app_rdm/config.py
This addresses https://github.com/zenodo/rdm-project/issues/203
It requires changes in three modules.
Stats: create a new index keeping track of the statistics that have been recalculated
Rdm-record: create a new task that reindexes all the documents identified in the previous step
invenio-app-rdm: Define the task
Please, let me know it things should be moved around
**Reminder**
By …
=> stats: Reindex documents after the statistics have been aggregated

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2467
=> landing-page: filter out deleted records from versions box

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1479
=> views: update import path

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ManageDefaultBrandingAction/ManageDefaultBrandingAction.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesListModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesSearch.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesSearchItem.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/message.overrides
* closes https://github.com/zenodo/rdm-project/issues/188
Preview:
Main flow:
Closer look:
Errors:
validation
http
backend
=> communities management: add possibility to change and remove branding

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/redirector/resource.py
- Closes https://github.com/zenodo/zenodo-rdm/issues/425
=> records-ui: expose thumbnail view

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/access-form.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/AccessRequestForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/form.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/message.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/table.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/accordion.overrides
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2464
=> landing page files: update styling for access status cases

invenio_app_rdm/config.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1454
depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/1465
Configure access-request notification builders. Also add `EmailResolver` to notification resolvers.
**Reminder** …
=> config: use access-request notificaton builder

invenio_app_rdm/__init__.py, setup.cfg
=> release: v12.0.0b2.dev38

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html
* closes https://github.com/zenodo/rdm-project/issues/274
=> templates: add conference acronym

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
=> record-versions: remove status filter

invenio_app_rdm/communities_ui/views/ui.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/tombstone.html
Partially closes Issue [#263](https://github.com/zenodo/rdm-project/issues/263)
**Reminder**
2. You …
=> tombstone: removed citation

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev41

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/meta.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/filters.py, tests/ui/test_export_formats.py
closes https://github.com/zenodo/rdm-project/issues/223
closes https://github.com/zenodo/rdm-project/issues/220
This work is all from @mfenner , I opened the PR here since I could not work on the original [PR](https://github.com/inveniosoftware/invenio-app-rdm/pull/2410) base (it was `front-matter:master`)
Tests are passing locally, failing in the CI since it depends from https://github.com/inveniosoftware/invenio-rdm-records/pull/1533
=> adding record exporter for SchemaorgJSONLDSerializer

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
=> details: check if files not empty in case we see a request details page

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/access-form.html
Closes https://github.com/zenodo/rdm-project/issues/307
**Reminder** …
=> ui: records: details: access-form: full_name none check

invenio_app_rdm/communities_ui/views/ui.py
* closes https://github.com/zenodo/rdm-project/issues/324
=> ui: allow slashes in communities urls

invenio_app_rdm/records_ui/views/decorators.py
* Redirects /uploads/:id to /records/:id when a draft is not found, so user can interchangeably use both links to access their records/uploads.
=> records: redirect /uploads/:id to /records/:id

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev47

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev48

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/deposit.html, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/deposits.py
* closes https://github.com/zenodo/rdm-project/issues/398
=> views: pass files locked flag to UI

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/description.html
Closes Issue [#393](https://github.com/zenodo/rdm-project/issues/393)
**Reminder**
2. You agree that you …
=> ui: added text break in description

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/card.overrides
=> ui: break up long community titles

invenio_app_rdm/administration/users/users.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/ImpersonateUser.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/SetQuotaAction.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RecordResourceActions.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RestoreConfirmation.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/TombstoneForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/UserActions.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/search/SearchResultItemLayout.js
Partially Closes Issue [#375](https://github.com/zenodo/rdm-project/issues/375)
- Removed Active & Blocked columns
- Added Id and Username columns
- Changed Verified and Confirmed columns to show checkmarks and show date in tooltip
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contrib …
=> ui: changes in user moderation table

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev54

invenio_app_rdm/requests_ui/views/requests.py
closes https://github.com/zenodo/rdm-project/issues/387
=> dashboard: fix user request details page

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev56

invenio_app_rdm/requests_ui/views/requests.py
closes https://github.com/zenodo/rdm-project/issues/467
=> views: retrieve published record if inclusion request

invenio_app_rdm/__init__.py, invenio_app_rdm/requests_ui/views/requests.py
=> V12.0.0b2.dev58

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/search/SearchResultItemLayout.js
Partially Closes Issue [#466](https://github.com/zenodo/rdm-project/issues/466)
**Reminder**
2. You …
=> ui: updated confirmation column value

invenio_app_rdm/__init__.py
=> release: v12.0.0b2.dev59

invenio_app_rdm/communities_ui/views/ui.py, setup.cfg
closes https://github.com/zenodo/rdm-project/issues/479
=> communities: rename search tab to records.

CHANGES.rst, invenio_app_rdm/__init__.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
Backport: #2516 
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.
=> Backport community logo placeholder fix to 11.x

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
- Fixes the versions not being displayed bug on the record landing page
**Reminder**
2. You agree that …
=> ui: fixed record version list display

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js
- closes #1873
**Screenshot (most recent)**
=> search: signal if more than 3 authors

invenio_app_rdm/config.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1619
=> config: enabled cff export format

invenio_app_rdm/config.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2543
=> config: enabled codemeta export format.

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/description.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessRequests/AccessRequestsTab.js, invenio_app_rdm/theme/webpack.py
Partially Closes Issue [#421](https://github.com/zenodo/rdm-project/issues/421)
**Reminder**
2. You …
=> editor: replaced ckeditor

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
Closes part of https://github.com/zenodo/rdm-project/issues/594
=> deposit form: add acronym to award titles

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/external_resources.html
=> external resources: align items

invenio_app_rdm/communities_ui/views/communities.py, invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/deposit.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/footer.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/page.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/site_footer.html, invenio_app_rdm/theme/templates/themes/default/invenio_app_rdm/header.html, invenio_app_rdm/theme/templates/themes/default/invenio_app_rdm/site_footer.html, setup.cfg
closes https://github.com/zenodo/horizon-zen/issues/46
=> Branded templates

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py
Closes Issue [#632](https://github.com/zenodo/rdm-project/issues/632)
- Renders only populated custom fields for Biodiversity
- Inlcuded floats as hyperlinks 
**Reminder** …
=> custom fields: fixed float fields hyperlinks

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides, invenio_app_rdm/theme/webpack.py
* closes https://github.com/zenodo/rdm-project/issues/649
=> deposit: add record to props of custom fields

CHANGES.rst, invenio_app_rdm/__init__.py, setup.cfg
=> Bump dependencies and release v12.0.0b2.dev68

invenio_app_rdm/communities_ui/views/communities.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/deposit.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitySubmission/RecordCommunitySubmissionModal.js, invenio_app_rdm/theme/templates/themes/default/invenio_app_rdm/site_footer.html, setup.cfg
* closes https://github.com/zenodo/zenodo-rdm/issues/691
=> record views: add dedicated community upload form route

invenio_app_rdm/communities_ui/views/communities.py, invenio_app_rdm/communities_ui/views/ui.py, invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/records_ui/views/records.py
Closes Issue [#689](https://github.com/zenodo/zenodo-rdm/issues/689)
P.s only review my commit
**Reminder** …
=> community: updated route for records page

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables
* closes https://github.com/zenodo/zenodo-rdm/issues/715
=> theme: add some css classes to display communities list on the record

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
* closes https://github.com/zenodo/zenodo-rdm/issues/727
=> css: add muted color link style

invenio_app_rdm/records_ui/views/records.py
- Closes https://github.com/inveniosoftware/invenio-communities/issues/1100
=> views: serialize UI community result

.github/workflows/tests.yml, invenio_app_rdm/administration/domains/__init__.py, invenio_app_rdm/administration/domains/domains.py, invenio_app_rdm/administration/templates/semantic-ui/invenio_app_rdm/administration/domains_search.html, invenio_app_rdm/administration/users/users.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/ImpersonateUser.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/SetQuotaAction.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/SetQuotaForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/domains/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/domains/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/domains/search/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/UserActions.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/api/api.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/api/routes.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/search/SearchResultItemLayout.js, invenio_app_rdm/theme/webpack.py, setup.cfg
Depends on https://github.com/inveniosoftware/invenio-users-resources/pull/124
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2575
=> Users admin

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/default_static_page.html
Partially Closes Issue [#196](https://github.com/inveniosoftware/invenio-administration/issues/196)
**Reminder** …
=> pages: added class for content

invenio_app_rdm/theme/templates/themes/default/invenio_app_rdm/site_footer.html
Closes Issue [#719](https://github.com/zenodo/zenodo-rdm/issues/719)
- center "verified" community in the site_footer, remove "learn more"
**Reminder**
1. You license your contribution under the …
=> Footer: updated theme site_footer

invenio_app_rdm/communities_ui/views/communities.py, invenio_app_rdm/communities_ui/views/ui.py, invenio_app_rdm/config.py, invenio_app_rdm/fixtures/pages.py, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/default_static_page.html
Closes Issue [#706](https://github.com/zenodo/zenodo-rdm/issues/706)
**Reminder**
2. You agree that you …
=> community: added static page for branded community

invenio_app_rdm/communities_ui/views/ui.py
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/743
**Reminder** …
=> menu: added submit submenu for branded comm

invenio_app_rdm/communities_ui/views/communities.py
closes https://github.com/zenodo/zenodo-rdm/issues/747
=> views: added metrics to themed community home page

invenio_app_rdm/communities_ui/views/communities.py
- Closes https://github.com/inveniosoftware/invenio-communities/issues/1108
=> communities-ui: update view permissions

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
=> details: fix files condition for anonymous access requests

invenio_app_rdm/communities_ui/views/ui.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/DisplayPartOfCommunities.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/DisplayVerifiedCommunity.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/ComputerTabletUploadsItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/MobileUploadsItem.js
- **search-ui: move up record item branded banne**
- **communities-ui: fix pages menu link generation**
- **search-ui: fix communities part-of display**
- **records-ui: move verified check icon to the right**
- **ui: temporarily disable record result item themed banner**
=> Branding fixes

setup.cfg
This PR changes the dependency from `pytest-black `to `pytest-black-ng`.  To improve consistency across invenio packages.
**Reminder** …
=> format: change pytest-black to pytest-black-ng

invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/urls.py, tests/ui/conftest.py, tests/ui/test_signposting_ui.py
See https://github.com/inveniosoftware/rfcs/pull/73
=> views: add signposting link to landing+download response headers

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html, invenio_app_rdm/theme/templates/themes/default/invenio_app_rdm/header.html
Closes Issue https://github.com/zenodo/ops/issues/331
**Reminder**
2. You agree that you have the right …
=> theme: moved banner position

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.en.html
Resolves https://github.com/inveniosoftware/invenio-app-rdm/issues/2241 and other general search help page improvements
**Reminder** …
=> templates: improve search help

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
Closes Issue https://github.com/zenodo/ops/issues/382
**Reminder**
2. You agree that you have the right …
=> css: added class for word-break

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/SearchResultItemLayout.js
closes https://github.com/zenodo/ops/issues/340
=> search: fix stats display for drafts

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html
Closes Issue https://github.com/zenodo/ops/issues/385
**Reminder**
2. You agree that you have the right …
=> code: updated url generation for repository url

invenio_app_rdm/__init__.py
=> release: v12.0.0b3.dev7

invenio_app_rdm/communities_ui/views/ui.py, invenio_app_rdm/ext.py
=> ext: add back removed community menu items

invenio_app_rdm/__init__.py
=> release: v12.0.0b3.dev8

invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/domains/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/AccessDropdown.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/CreateAccessLink.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchResultContainer.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsers/AccessUsers.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsers/UserAccessSearchResult.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/table.overrides
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2436
Owner view:
"Manager" view:
Flow:
Mobile:
=> share access: manage user grants in "People" tab

invenio_app_rdm/ext.py
requires https://github.com/inveniosoftware/invenio-communities/pull/1125
=> ext: space-out community menu items

invenio_app_rdm/__init__.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/domains/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/AccessDropdown.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/CreateAccessLink.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchResultContainer.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsers/AccessUsers.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsers/UserAccessSearchResult.js, setup.cfg
- **installation: bump rdm-records and communities**
- **📦 release: v12.0.0b3.dev9**
=> Bump deps and release v12.0.0b3.dev9

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/domains/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RecordResourceActions.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/AccessDropdown.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/CreateAccessLink.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchResultContainer.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksTab.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsers/AccessUsers.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsers/AddUserAccessModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsers/UserAccessSearchResult.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/api/api.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.overrides
* share access: add create new grants modal
* add notification on add grant
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2593
Mobile:
Updated dropdown with “all versions” emphasizing
=> Add people functionality

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js
- Fixes the regex, which wrongly skipped the last character of the URL (if it wasn't a `,`,  `;`, or `.`)
- Trims trailing dots from the matched URL (too difficult to do with regex).
**Frontend**
**Reminder**
1. …
=> records-ui: citation urlize for trailing dot

invenio_app_rdm/records_ui/views/records.py
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/819
- Added record in PreviewFile for accessing the manifest url to be passed down to mirador previewer
**Frontend**
**Reminder** …
=> previewer: added record to the PreviewFile

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/UserActions.js
* Previously, the loading state was only reset upon successful completion of the user action. If an error occurred, such as a 403, the UI incorrectly remained in a "loading" state, leaving the button disabled and showing a loading indicator indefinitely. This change ensures that the loading state is reset under all circumstances by moving the setState call to a finally block.
* Removed the line resetting the loading state from the try block.
* Added a finally block to reset the loading state whether the promise is resolved or rejected.
Before:
After:
* If you have added [third-party code (copy/pasted or new …
=> Administration UI: Reset Loading State In Finally Block

invenio_app_rdm/config.py, invenio_app_rdm/ext.py
Currently, submenus on the user dashboard [are hard-coded](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/users_ui/views/ui.py#L70), making their configuration hard.
This PR moves them to a config-variable, which allows to:
- more easily add further submenus (by way of configuration)
- make use of submenus' many options by configuring the corresponding kwarg, e.g. `visible_when`-kwarg to tune visibility
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an …
=> dashboard: make menus configurable

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
Allowing the height and width properties to be overridden from css for any instance as per the requirement
- https://github.com/inveniosoftware/invenio-app-rdm/pull/2550#discussion_r1570871550
Added banner to be displayed in case of fallback if media files are not processed or if the files are viewed in preview
- https://github.com/zenodo/zenodo-rdm/issues/840
**Frontend**
**Reminder**
By using …
=> previewer: hide media_files and configured iframe dim

invenio_app_rdm/records_ui/views/decorators.py
closes https://github.com/zenodo/zenodo-rdm/issues/852
=> views: pass draft and record for lock files check

invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py
* add concept doi to parent record
* apply community changes only if community exists
* update record schema to newest
* fix small coding style errors
=> migrate: fix bugs

invenio_app_rdm/__init__.py, invenio_app_rdm/ext.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/deposit.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/restricted_tombstone.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/ShareModal.js
* closes https://github.com/inveniosoftware/product-rdm/issues/178
Tombstone page for record restriction:
=> record restriction grace period: add tombstone page

invenio_app_rdm/config.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/153
=> config: add notification builders

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/ShareModal.js
closes https://github.com/zenodo/ops/issues/448
edited by Manuel 🥷
=> records-ui: handle missing `grants` field

invenio_app_rdm/records_ui/views/decorators.py, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/ShareModal.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2684
=> deposit: remove login required from deposit edit

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js
* Closes https://github.com/zenodo/zenodo-rdm/issues/847.
=> records-ui: fix trailing dot issue in citation text

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
* Fixes inveniosoftware/invenio-vocabularies#342
* Check first the pull request inveniosoftware/invenio-vocabularies#343
Places in other repos which might need to be modified to also include country_name:
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license …
=> vocabularies: pass on country_name in deserializeFunder

invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/subcommunity/index.html, invenio_app_rdm/requests_ui/views/requests.py
Close https://github.com/inveniosoftware/invenio-communities/issues/1150
At the moment very basic implementation
**Frontend**
**Reminder** …
=> requests: add subcommunity request details page

invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/subcommunity/index.html
closes https://github.com/zenodo/zenodo-rdm/issues/883
=> subcommunities: fixed back button for request page

invenio_app_rdm/config.py
Closes https://github.com/zenodo/zenodo-rdm/issues/881
=> config: add subcommunity request notifications

invenio_app_rdm/config.py
=> global: add meta generator tag

invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/subcommunity/index.html
closes https://github.com/zenodo/zenodo-rdm/issues/905
=> Subcommunities: fix request "back" button

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/80
=> header: adapt menu to responsive view

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/SearchResultItemLayout.js
This PR fixes Drafts with empty titles that don't have usable links in the administration panel from the frontend.
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2716
**Frontend**
**Reminder** …
=> Administration: Provide Fallback Value For Missing Draft Title

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagementDropdown.js
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2227
**Frontend**
**Reminder**
2. You agree that you …
=> Preview: Hide Community Dropdown Menu When Is Draft

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/records_ui/views/records.py
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/931 
**Frontend**
**Reminder** …
=> preview: update file previewer check in metadata

invenio_app_rdm/__init__.py, invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/creatibutors.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html
Fixes https://github.com/inveniosoftware/invenio-vocabularies/issues/348
=> config: import vocab readers, transformers, writers consistently

invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py
* list points which were tested
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2717
=> migration: add parent doi handling

invenio_app_rdm/cli.py, invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/creatibutors.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/draft_not_found.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html, invenio_app_rdm/records_ui/views/__init__.py, invenio_app_rdm/records_ui/views/records.py, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagementDropdown.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/CreateAccessLink.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchResultContainer.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/ShareModal.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py
this PR has cherry-picked commits from master to incorporate into the next RC of v12
=> Maint v12 cherry picked

invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html, invenio_app_rdm/requests_ui/views/requests.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/176
=> requests: fix small ui bugs

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1786
=> deposit: pass record to publish button

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsersGroups/AddUserGroupAccessModal.js
This will fix the editor's loss of content after losing focus in add people modal when activating notify people
Related to: https://github.com/inveniosoftware/react-invenio-forms/pull/249
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including …
=> Editor: Update RichEditor to use inputValue

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/communityRecordsSearch/CommunityRecordsSearchAppLayout.js
This reverts commit 2bd15ea94e2c4282f345812c41c943dd515a470d.
=> Revert "ui: add comma separator to community req total"

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2767
=> DepositForm: Add search_on_focus attribute to subjects RemoteSelectField

invenio_app_rdm/theme/webpack.py
* closes https://github.com/zenodo/rdm-project/issues/657
=> package: bump react-invenio-forms

.github/workflows/tests.yml, invenio_app_rdm/__init__.py, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html, invenio_app_rdm/requests_ui/views/requests.py
Backport of:
* https://github.com/inveniosoftware/invenio-app-rdm/pull/2762
* https://github.com/inveniosoftware/invenio-app-rdm/pull/2773 (partial, only the CI part)
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2779
=> v12 backports for CI & requests

setup.cfg
Pin upper version of `invenio-search-ui`, as v2.9.0 introduces a js dependency change not compatible with other module versions (`"react-invenio-forms": "^3.0.0"` -> `"react-invenio-forms": "^4.0.0"`)
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/ …
=> deps: pin upper version of search-ui to <2.9.0

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsersGroups/AddUserGroupAccessModal.js
Fixes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2752
=> AddUserGroupAccessModal: Use suggest API for finding users

invenio_app_rdm/config.py
Closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2746
=> config: Bump records index version to v7.0.0

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/creatibutors.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html
Fixes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2692
Before
After
=> records_ui: creatibutors: Display creator roles

invenio_app_rdm/config.py
Closes https://github.com/inveniosoftware/invenio-vocabularies/issues/322
=> config: add subjects datastream config

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/details.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html
- fix to display Sizes (wasn't displaying in v12)
- simplify formats as well
I will backport this to maint-v12.x when merged.
=> sidebar: display 'Sizes' properly [+]

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/details.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsersGroups/AccessUsersGroups.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/ShareModal.js, run-tests.sh
Backporting. Will merge after tests pass.
- **share-modal: account for system created records**
- **sidebar: display 'Sizes' properly [+]**
=> backport sizes and share modal

run-tests.sh
=> tests: use opensearch2

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
Same as https://github.com/inveniosoftware/invenio-app-rdm/pull/2807, but targeted to `master` rather than `maint-v12.x`
=> Deposit form: Provide props to overridable components (master)

invenio_app_rdm/requests_ui/views/requests.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/158
=> ui: propagate permission check for community requests view

invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py
Bringing the v12 upgrade script to master: https://github.com/inveniosoftware/invenio-app-rdm/pull/2814
=> Upgrade script: Mint the new concept DOI for each upgraded record [master]

invenio_app_rdm/records_ui/views/deposits.py
Closes Issues: https://github.com/inveniosoftware/invenio-rdm-records/issues/1788
Depends on: https://github.com/inveniosoftware/invenio-rdm-records/pull/1789 - tests 
**Frontend**
**Reminder**
1. You license …
=> deposit: renamed get quota function

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/accordion.overrides
* closes https://github.com/inveniosoftware/invenio-jobs/issues/49
=> theme: fix accordion rotation

invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/987
**Before:**
**After:**
**Frontend**
**Reminder**
2. You …
=> css: added class for padding removal

invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py
- account for deleted Communities . Those don't have `"access"` raising an error.
- **[edit 2024-09-04]** second change : concept DOIs should only be minted for published records (`register_or_update` is called on publishing typically) and in the migration script it would have been called on drafts too. `register_or_update` already covers private/public record though which is great.
=> migration: account for deleted communities and draft concept DOI

CHANGES.rst, invenio_app_rdm/__init__.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/communityRecordsSearch/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/DisplayPartOfCommunities.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/accordion.overrides, invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py, invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html
- **search-result: provide key to part of community array element**
- **search-result: namespace overridable id for community search results**
- **theme: fix accordion rotation**
- **css: added class for padding removal**
- **migration: account for deleted communities and draft concept DOI**
- **admin-records: account for system owned records**
- **admin-records: add reference to gh issue**
- **release: v12.0.6**
=> release v12.0.6

invenio_app_rdm/config.py
Add group resolver to notification resolvers.
This will allow to specify a group entity in a notification and be resolved correctly.
**Frontend**
**Reminder**
1. You …
=> config: add group resolver for notifications

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/deposit.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/index.js
* Expose `RECORDS_RESOURCES_ALLOW_EMPTY_FILES` for UI control
* Depends on: https://github.com/inveniosoftware/invenio-rdm-records/pull/1802
**Frontend**
**Reminder**
1. You license your contribution under the …
=> Deposit: Expose ALLOW_EMPTY_FILES config for UI Control

invenio_app_rdm/config.py
=> feat: display package version in administration panel

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RemoveFromCommunity/RemoveFromCommunityAction.js
closes: https://github.com/CERNDocumentServer/cds-rdm/issues/88
=> Assets: RemoveFromCommunity: Fix error message display

CHANGES.rst, invenio_app_rdm/__init__.py, invenio_app_rdm/communities_ui/templates/semantic-ui/invenio_communities/collections/collection.html, invenio_app_rdm/communities_ui/views/communities.py, invenio_app_rdm/communities_ui/views/ui.py, invenio_app_rdm/config.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/collectionRecordsSearch/index.js, invenio_app_rdm/theme/webpack.py, setup.cfg
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1820
--- 
**Screenshots**
I have the following collections:
- EU (Community)
- Funding programmes (Tree)
- Horizon 2020 collection (2 records)
- Open access collection (1 record)
- Restricted access  collection (1 record)
e654f0be">
=> collections: added collection page with minimal UI

CHANGES.rst, invenio_app_rdm/__init__.py, setup.cfg
Release fixes inveniosoftware/invenio-vocabularies#401
=> installation: bump invenio-communities & invenio-rdm-records & 📦 release: v13.0.0b1.dev8

invenio_app_rdm/config.py
* Partially closes inveniosoftware/invenio-vocabularies#393
* Should be green after inveniosoftware/invenio-vocabularies#392 is merged and released
This Pull Request configures the common OpenAIRE datastream readers/transformers/writers.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contr …
=> config: vocabularies Datastream common OpenAIRE

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js
Closes Issue https://github.com/inveniosoftware/invenio-communities/issues/1227
**Frontend**
**Reminder**
2. You agree …
=> ui: added theme classes to record list

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/DisplayPartOfCommunities.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js
**Record Result List**
**Record Landing Page**
**Record Community Header**
**Frontend**
**Reminder**
2. You agree that …
=> ui: added icon for verified community

invenio_app_rdm/administration/records/records.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/default_static_page.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/settings/notifications.html
* change record to lowercase as I double-checked with other references and looks like it is the right way to be lowercase see:
[moderation](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/administration/user_moderation/user_moderation.py#L25)
[users](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/administration/users/users.py#L54)
[domains](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/administration/domains/domains.py#L40)
I also checked in other packages see:
[banners](https://github.com/inveniosoftware/invenio-banners/blob/master/invenio_banners/administration/banners.py#L23)
* Remove what seems to be a typo in the template
Ticks in all boxes and 🟢 on …
=> chore: fix Typos

invenio_app_rdm/config.py, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/page_cover.html
fixes: https://github.com/CERNDocumentServer/cds-rdm/issues/190
=> templates: Override page_cover to add banner to login

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js
closes: https://github.com/CERNDocumentServer/cds-rdm/issues/115
=> theme: header_login: Optimize element search and add translations

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/domains/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/search/SearchResultItemLayout.js
the problem is that you cannot open onClick in new tab
Close #2898 
The problem is that onClick means that you cannot copy the link address or open it in a new tab
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-lic …
=> bug: use href instead of onClick

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/242
=> assets: add overridable component section extender

invenio_app_rdm/__init__.py
=> release: v13.0.0b1.dev16

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/SearchResultItemLayout.js
Close #2898 
Using the same fixed link as used in [ManageButton.js](https://github.com/carlinmack/invenio-app-rdm/blob/link-user/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ManageButton.js#L33)
**Frontend**
**Reminder** …
=> admin: add link to user in records and drafts

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/search/SearchResultItemLayout.js
Close #2898 
> Please describe briefly your pull request
Not much has changed visually besides some nicer spacing, but the icons have been linked to the user's ID on ORCiD/GitHub
I deprecated the use of `BoolFormatter` here as it would be repetitive to check whether the icon should be displayed twice
**Frontend**
**Reminder** …
=> admin: link GitHub and ORCiD icons to sites

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/table.overrides
Close #2898 
**Before**:
**After**:
---
**Before**:
**After**:
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the current …
=> admin: increase title length and fix mobile

invenio_app_rdm/__init__.py, setup.cfg
=> V13.0.0b1.dev17

invenio_app_rdm/records_ui/views/deposits.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/207
=> custom fields ui: add sorting by title

invenio_app_rdm/config.py, invenio_app_rdm/upgrade_scripts/migrate_12_0_to_13_0.py
- **config: removed unecessary INDEXER_DEFAULT_INDEX**
- **upgrades: remove record JSONSchema version bump**
=> Undo record JSONSchema major bump

invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html
related: https://github.com/inveniosoftware/invenio-app-rdm/pull/2911
=> semantic-ui: users: header: Pass entrypoint namespace in url_for

invenio_app_rdm/communities_ui/views/ui.py
Fixes: https://github.com/inveniosoftware/invenio-communities/issues/1250
=> communities_ui: views: Add RecordPermissionDeniedError Handler

invenio_app_rdm/__init__.py
=> release: v13.0.0b1.dev19

invenio_app_rdm/config.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html
Fixes Issue https://github.com/inveniosoftware/invenio-vocabularies/issues/433
**Frontend**
**Reminder**
2. You agree …
=> creatibutors: added edmo to the list of identifiers

invenio_app_rdm/config.py, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/subcommunity-invitation/index.html, invenio_app_rdm/requests_ui/views/requests.py
Close https://github.com/zenodo/zenodo-rdm/issues/1061
Relies on invenio-communities PR for tests to pass
**Frontend**
**Reminder**
1. You license your contribution …
=> requests: add subcommunity invitation request details page

setup.cfg
- Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2924
=> installation: bump invenio-access to remove invenio-admin dependency

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
The div is opened on [line 28](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html#L28)
=> bug: close unclosed div

invenio_app_rdm/config.py
- **config: make OAI-PMH record index dynamic**
=> v12 fix oaiserver

CHANGES.rst, invenio_app_rdm/__init__.py, setup.cfg
Release for the OAI-PMH backport
=> release: v12.0.13

.github/workflows/pypi-publish.yml
=> ci: update PyPI publish workflow to use shared configuration

invenio_app_rdm/config.py
Close https://github.com/inveniosoftware/invenio-rdm-records/issues/1903
Close https://github.com/inveniosoftware/invenio-communities/issues/1261
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including …
=> config: add record and membership comment notifications

CHANGES.rst, invenio_app_rdm/__init__.py
=> release: v13.0.0b1.dev30

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/343
=> resultView: fix truncateed description

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
=> globals: site.overrides: Increase pdf preview iframe height

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/meta.html
* Partially fixes #2937
* See description in linked ticket
**Frontend**
**Reminder**
2. You agree that you have the right …
=> meta: FAIR signposting level 1 support (link rel item)

CHANGES.rst, invenio_app_rdm/__init__.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/base.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js
=> V13.0.0b2.dev6

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/config.js
Closes Issue https://github.com/inveniosoftware/invenio-rdm-records/issues/1980
**Frontend**
**Reminder**
2. You agree that you have the right to …
=> config: updated severity label text

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.sv.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/statistics.sv.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/versioning.sv.html
Auto-generated translation, requires a review
**Frontend**
**Reminder** …
=> i18n: add `sv` translation for help pages

CHANGES.rst, invenio_app_rdm/__init__.py, invenio_app_rdm/administration/records/records.py, invenio_app_rdm/administration/user_moderation/user_moderation.py, invenio_app_rdm/administration/users/users.py, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/access-form.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/contact.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/licenses.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/version.html, invenio_app_rdm/records_ui/views/deposits.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/ImpersonateUser.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/ImpersonateUserForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RestoreConfirmation.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/TombstoneForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/userModeration/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/AccessRequestForm.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchItem.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/files_integrity_report/email/files_integrity_report.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/footer.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/intro_section.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/macros/records_list.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/site_footer.html, invenio_app_rdm/theme/templates/themes/default/invenio_app_rdm/site_footer.html
Please make sure to merge the following before merging this one:
https://github.com/inveniosoftware/invenio-app-rdm/pull/2998
**Frontend**
**Reminder** …
=> I18n: Mark Strings for Translation Backport

CHANGES.rst, invenio_app_rdm/__init__.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js, setup.cfg
* allow pagination in license modal
* closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2691
Changes search config prop for the LicenseField to allow pagination in LicenseModal as suggested in https://github.com/inveniosoftware/invenio-app-rdm/issues/2691.
Depends on: https://github.com/inveniosoftware/invenio-rdm-records/pull/1946
**Frontend**
**Reminder**
By using GitHub, you have …
=> deposit: align license search config w/ funding

invenio_app_rdm/theme/assets/semantic-ui/translations/invenio_app_rdm/messages/index.js
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/3013
**Frontend**
**Reminder** …
=> fix: Restore Messages `index.js` and Remove Unused Imports

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html
Backport for https://github.com/inveniosoftware/invenio-app-rdm/pull/2932
**Frontend**
**Reminder** …
=> Fix-undefined-records-attrs-backport

CHANGES.rst, invenio_app_rdm/__init__.py
=> Backport-release

invenio_app_rdm/records_ui/views/deposits.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/2011
=> deposits: use optional doi validator method

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsersGroups/AccessUsersGroups.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsersGroups/UserGroupAccessSearchResultItem.js
- Fix for share options breaking on access granted to deleted user
**Frontend**
**Reminder**
2. You agree that you have the right to license your …
=> bug-fix: added optional chaining for user avatar

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/licenses.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/381
=> deposit: add copyrights field

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
Mark "Funding" for translation. Will resolve https://github.com/inveniosoftware/invenio-app-rdm/issues/2541
**Frontend**
**Reminder**
2. You agree …
=> i18n: mark string for translation

invenio_app_rdm/administration/audit_logs/__init__.py, invenio_app_rdm/administration/audit_logs/audit_logs.py, invenio_app_rdm/administration/templates/semantic-ui/invenio_app_rdm/administration/audit_logs.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/auditLogs/index.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/auditLogs/search/SearchResultItemLayout.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/auditLogs/search/index.js, invenio_app_rdm/theme/webpack.py, setup.cfg
closes: https://github.com/CERNDocumentServer/cds-rdm/issues/410
=> administration: Add Audit Logs Admin Panel UI

CHANGES.rst, invenio_app_rdm/__init__.py
=> release: v13.0.0b3.dev8

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js
=> MathJax: add typesetting to the citations box

invenio_app_rdm/fixtures/pages.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2278
=> fixtures: make content template optional

CHANGES.rst, invenio_app_rdm/__init__.py
=> release: v13.0.0b3.dev10

invenio_app_rdm/config.py
NEEDS https://github.com/inveniosoftware/invenio-jobs/pull/80
=> beat: add delete job logs recurrent task

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html
closes https://github.com/CERNDocumentServer/cds-rdm/issues/484
=> details: pass scheme on related identifiers url generator

invenio_app_rdm/records_ui/views/deposits.py
* previously, the deposit form would show values from the configuration that might be different from the actually effective quota
This is a copy of https://github.com/inveniosoftware/invenio-app-rdm/pull/3044 without CHANGES.rst. I'm making a new PR due to permission issues.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-servi …
=> deposit: report actual file quota rather than configured values

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/stats.html
Closes issue https://github.com/zenodo/zenodo-rdm/issues/540
**Frontend**
**Reminder**
2. You agree that you have the right to license your …
=> ui: fixed caret trigger in stats

CONTRIBUTING.rst, docs/configuration.rst, invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/intro_section.html
close https://github.com/inveniosoftware/invenio-app-rdm/issues/3098
This could be merged now or await for closer to release of v13 (release of new docs). Since this is master branch of invenio-app-rdm, merging now is actually fine.
=> links: update doc links to updated ones

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/doi.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/CopyButton.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ExportDropdown.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/theme.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides, invenio_app_rdm/theme/webpack.py, invenio_app_rdm/upgrade_scripts/migrate_12_0_to_13_0.py, setup.cfg
- semantic-ui: landing_page: add click event for cite all versions
- semantic-ui: componenets: add url fetching in copy button   * remove dependency on react-copy-to-clipboard   * use navigator.clipboard.copy
- semantic-ui: landing_page: ExportButton: Add copy button
- semantic-ui: components: CopyButton: add size prop
- templates: macros: doi: Add copy button for DOIs
- version: bumped invenio-s3 version to include multipart upload
- upgrade_scripts: handle thesis custom field migration
- migration: optimize script
=> maint v13 x cherry picked 2

CHANGES.rst, invenio_app_rdm/__init__.py, invenio_app_rdm/theme/assets/semantic-ui/translations/invenio_app_rdm/package-lock.json
- fix: package.json and package-lock mismatch
=> fix translations build

invenio_app_rdm/theme/templates/semantic-ui/invenio_communities/default_static_page.html
- Needed default wrapper for branded communities.
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under …
=> templates: added default_static_page for communties

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/macros/records_list.html, invenio_app_rdm/theme/templates/semantic-ui/invenio_communities/default_static_page.html
- templates: added default_static_page for communties
- fix: import `overridable-registry.js` in `records_list` macro
- fix: license due to copy pasting
- release: v13.0.0rc7
=> maint v13 x cherry picked 3

CHANGES.rst, invenio_app_rdm/__init__.py, invenio_app_rdm/upgrade_scripts/migrate_12_0_to_13_0.py
- migration: improve text in v13 upgrade script
- release: v13.0.0rc8
=> rel v13 0 0 rc8

CHANGES.rst, invenio_app_rdm/__init__.py, invenio_app_rdm/upgrade_scripts/migrate_12_0_to_13_0.py
- fix(migration): wrong variable used
- release: v13.0.0rc9
=> rel v13 0 0 rc9

invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/record-deletion/index.html, invenio_app_rdm/requests_ui/views/requests.py
- Added template for record deletion request type
- Fixed an issue with resolving deleted record requests.
=> UI: requests: add template for record deletion

invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/search.overrides
Closes https://github.com/inveniosoftware/invenio-requests/issues/428
=> requests: add request action_accept permissions to UI

CHANGES.rst, invenio_app_rdm/__init__.py, setup.cfg
=> V14.0.0b0.dev0

CHANGES.rst, invenio_app_rdm/__init__.py, invenio_app_rdm/theme/assets/semantic-ui/translations/invenio_app_rdm/package-lock.json
=> V4.0.0b0.dev1

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/external_resources.html, invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/licenses.html, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/theme.js, invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page/licenses.less
Before and after, both `External resources` and `Rights` are now consistent with the `Details` section
**Frontend**
**Reminder** …
=> UI: Improve display of Rights and External resources section

invenio_app_rdm/upgrade_scripts/migrate_12_0_to_13_0.py
Needed for upgrade to v13. I will backport when merged.
I also then used `pipenv run invenio vocabularies update --vocabulary affiliations --origin ror-http` instead of `import`. I will make a separate PR for that in docs tomorrow.
=> Provide migration to confirm affiliations entries to new shape

invenio_app_rdm/upgrade_scripts/migrate_12_0_to_13_0.py
**BACKPORT - merging when tests pass**
- **v13-migration: update affiliation entries**
- **v13-migration: update name entries**
=> affiliations names migration

invenio_app_rdm/records_ui/views/decorators.py, tests/ui/test_file_download.py
- Closes #2726.
- **test(views): cover deleted record file handling**
- **fix(views): redirect deleted record file downloads**
* When accessing a file download of a deleted record, return a 302
redirect to the record page. This is to make sure that we display the
record's "410 Gone" tombstone page response.
=> Handle deleted record files tombstone redirect

invenio_app_rdm/upgrade_scripts/migrate_12_0_to_13_0.py
* Adds the recently added `is_machine` field to the record views and
file downloads event stats mappings. Only updates the latest two
indices, since they might still be actively receiving/processing
events.
=> feat(upgrade_scripts): add event stats mapping update for v13

invenio_app_rdm/administration/moderation/requests.py, invenio_app_rdm/administration/templates/semantic-ui/invenio_app_rdm/administration/requests_details.html, invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/record-deletion/index.html, invenio_app_rdm/requests_ui/views/requests.py, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordDeletion/DeletionModal.js, invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
=> i18n: add translated record deletion reason
