setup.py
tests/api/test_record_api.py

@fenekku  you might wanna change the deps pinned:
- invenio to just >= on the bundle to avoid future releases cuz of it. Or just expand all bundles.
- rdm-records accordingly to what its released.

dependencies: expand metadata and files bundles

---

invenio_app_rdm/config.py

- This approach has the advantange of being very simple
and non-coupling. But it is new.
- Using ext.py could achieve the same thing, but it's more code
- closes #36

config: set external configuration via config.py

---

invenio_app_rdm/config.py
invenio_app_rdm/theme/assets/scss/invenio_app_rdm/footer.scss
invenio_app_rdm/theme/assets/scss/invenio_app_rdm/theme.scss
invenio_app_rdm/theme/templates/invenio_app_rdm/footer.html
invenio_app_rdm/theme/templates/invenio_app_rdm/record_view_page.html

Changes:
- Navbar gradient inverted again in order to have the blue background behind `InvenioRDM` logo.
- Footer color was not matching. Now it follows the same blue.
- In the main page the app text has been changed to reflect the product page ("The turn-key...").
- "Powered by InvenioRDM" text in the footer.
- Removed update date from record view.
- Changed "Sign up" button color. Lars pointed out that red might reflect "negative" actions. Changed to green. The original "orange/yellow" did not match at all. We should work on a palette of colors. Feel free to change this color if needed.
Ready to be merged :)

ui: several css fixes on color and default text changes

---

invenio_app_rdm/config.py
invenio_app_rdm/theme/templates/invenio_app_rdm/record_view_page.html
invenio_app_rdm/theme/views.py

- closes #43 
- kept it basic for now: the first (alphanumerically) previewable files is previewed and that's it.

43 files previewer

---

invenio_app_rdm/config.py
invenio_app_rdm/theme/templates/invenio_app_rdm/record_view_page.html

Changes:
* `RECORDS_UI_ENDPOINTS` naming. Since some code is reused from `invenio-previewers` it was looking for `recid_files` and `recid_previewer` endpoing and not finding them. Now it is consistent.
Example:
``` console
curl -k -XPUT https://localhost:5000/api/records/54t33-38526/files/test.pdf -H "Content-Type: application/octet-stream" --data-binary @test.pdf
```
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/51

ui: fix files preview in records view

---

invenio_app_rdm/theme/assets/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositApiController.js
invenio_app_rdm/theme/assets/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
invenio_app_rdm/theme/assets/js/invenio_app_rdm/deposits/RDMDepositForm/components/ArrayTitlesItem.js
invenio_app_rdm/theme/assets/js/invenio_app_rdm/deposits/RDMDepositForm/components/ResourceTypeField.js
invenio_app_rdm/theme/assets/js/invenio_app_rdm/deposits/RDMDepositForm/components/index.js
invenio_app_rdm/theme/assets/js/react_invenio_forms/core/AccordionField.js
invenio_app_rdm/theme/views.py

This adds the title and resource type field on the deposit/new endpoint.
**Requirement**
- Requires fenekku/dump_vocabularies branch from invenio-rdm-records (see inveniosoftware/invenio-rdm-records#91) to get the empty record dump and the vocabulary dump
**TODO**
- add it on the edit endpoint
- investigate the null initial values
It can nevertheless be reviewed and merged (at least once this email_validator issue is fixed upstream)

Add title and resource type fields

---

.gitignore
invenio_app_rdm/theme/assets/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/AffiliationField.js
invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/ContributorsField.js
invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/CreatorOrContributorField.js
invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/CreatorsField.js
invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/IdentifierField.js
invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/ResourceTypeField.js
invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/TitlesField.js
invenio_app_rdm/theme/assets/js/react_invenio_deposit/components/index.js
invenio_app_rdm/theme/assets/js/react_invenio_forms/core/ArrayField.js
invenio_app_rdm/theme/assets/js/react_invenio_forms/core/FieldLabel.js
invenio_app_rdm/theme/assets/js/react_invenio_forms/core/SelectField.js
invenio_app_rdm/theme/assets/js/react_invenio_forms/core/index.js
run-tests.sh
setup.py

Adds the Creators and the Contributors Fields. In so doing also adds: IdentifierField and AffiliationField. These fields will be moved to react-invenio-deposit when the package is deployable.
A lot of structuring / decisions / experiments were made that would be worth discussing:
- **Current invenio-rdm-records more than mockups is followed.** Rather than go for all the niceties of the mockup, re-use of existing components mapping *directly* to the data model was favoured. For example, since the current invenio-rdm-records API expects an identifier value and its scheme to be passed to it, so does the form. The form does not try to guess the scheme from the identifier or hide the scheme field. There is pressure to just get a deposit page, so letting all fields be manually "fillable" is …

[follows from #113 ] Add Creators and Contributors Fields

---

.editorconfig
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
invenio_app_rdm/theme/templates/invenio_app_rdm/deposits/forms/deposits.html

First pass at deposit page styling.
- styles:
* action buttons
* accordion label + dropdown
* access-right
- adds placeholders
* contact support
* Files, Identifiers, Recommended Information sections
Looks like:
Needs: https://github.com/inveniosoftware/react-invenio-deposit/pull/28 merged in first
closes #119

119 style deposit page first pass

---

setup.py

- Moves s3 installation dependency from cookiecutter-invenio-rdm to
invenio-app-rdm.

installation: move s3 extension from cookiecutter

---

setup.py

This adds the version of invenio-rdm-records that has the bibliographic records Resource. It is now up to invenio-app-rdm to register it on the application.
From here on, @zzacharo is on it from what I understood. You can continue on this branch if you want, I won't touch it anymore.

dependencies: bump invenio-rdm-records to 0.15.0

---

invenio_app_rdm/theme/views.py
invenio_app_rdm/version.py
setup.py
tests/api/test_record_api.py

requires https://github.com/inveniosoftware/invenio-rdm-records/pull/139
tests: 
- removed `test_record_read_unregistered_pid` since it is the same than create a draft and read it (i.e. the PID is still not registered since it is a draft).

resources: integrate drafts resource

---

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/deposits/uploads.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/search.html
invenio_app_rdm/theme/webpack.py
invenio_app_rdm/version.py
setup.py

- correct `bestmatch` search order to work with new records-resources backend
* :WARNING: `bestmatch` is now used on the UI AND the API as opposed
to `bestmatch` in the UI and `-bestmatch` in the API. This is a breaking
change from the prior Invenio search interface. Made an issue to revisit
and discuss: https://github.com/inveniosoftware/invenio-records-resources/issues/74
- revert uploads page since user/records search is not implemented yet
- bump react-invenio-deposit to v0.5.0 to fix missing publication date
- release v0.12.5

Manual testing fixes

---

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/search.html

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/288
**NOTE**: I personally prefer "Most recent" as text. But put "newest" since is the name that was given in `records-resources`
WAIT TO RELEASE TO INCLUDE RDM-RECORDS BUMP

ui, search: replace most recent sorting option by newest

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search/components.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js

Closes #390
All UI labels/info are used now. for each item the entire area is clickable and goes to the upload edit page:

Fix upload and search results item

---

invenio_app_rdm/config.py
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/search.less
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/deposits/forms/deposits.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/deposits/uploads.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html

- remove specialized header templates {DEPOSITS,SEARCH_UI}_HEADER_TEMPLATE
- fix header.html's html
Longer term things to look into:
- move all frontpage html + less + images into cookiecutter: made an issue for it: https://github.com/inveniosoftware/invenio-app-rdm/issues/407
- we can reduce html nesting (I've collapsed a few layers in my instance)
- `invenio-cli watch` can be slow
- Had to `invenio-cli assets update` and/or restart even if running `invenio-cli watch`
(don't know what we can do, but a better update experience would be nice)

ui: improve some customization aspects [+]

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less

closes https://github.com/inveniosoftware/react-invenio-deposit/issues/87
Screenshot:
It's essentially 3 lines high rather than 1.

ui: enlarge description rich text editor height

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/footer.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/frontpage.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/navbar.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/footer.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/frontpage.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_frontpage.html

* Adds responsive navbar, footer and frontpage,
* partially addresses #259 and #170

styles: Fixes mobile layout

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/RDMDepositForm/RDMDepositForm.js

* Removes the initial license from invenio-app-rdm
* Moves it to the default serializer in react-invenio-deposit

deposit: move initial license to the serializer

---

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/landing_page/details/details.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/landing_page/macros/detail.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/landing_page/record_landing_page.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/search.html
invenio_app_rdm/theme/views.py
invenio_app_rdm/version.py
setup.py

Views are in charge of dereferencing record relations. This is *not ideal*, but since it uses records-ui endpoints (and not the service layer) it cannot be implemented as per [vocabularies RFC](https://codimd.web.cern.ch/I2ES9IjSRj-WFM2zUC1tKg#Presentation-layer)
Requires https://github.com/inveniosoftware/invenio-rdm-records/pull/319

Languages aggs

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposits/search/components.js
invenio_app_rdm/version.py

Can see several not complete deposit, the last one is actually fully empty!

assets: fix creator name requirement on deposit search

---

LICENSE
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/landing_page/record_landing_page.html
invenio_app_rdm/theme/webpack.py

closes inveniosoftware/invenio-rdm-records#352
remove import of invenio-communities JS code in the record landing page
also, add 'yup' as a webpack dependency because that's required by react-invenio-deposit and was only specified as a dependency in invenio-communities

Remove import of Invenio-Communities JS

---

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/landing_page/details/side_bar.html

closes #508 
**note**: the JSON export still points to `/coming-soon`

Disable sidebar elements

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less

This PR is part of inveniosoftware/react-invenio-deposit#196
gives the form fields and help texts some spacing see screenshot

style: modified css for more spacing

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less

closes inveniosoftware/react-invenio-deposit#88
not sure about the size of top-level fields - if its too big, see screenshots.
*screenshot*

form: sub field labels font-weight to normal

---

invenio_app_rdm/config.py
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/export_page.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/landing_page/details/side_bar.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/landing_page/export_page.html
invenio_app_rdm/theme/utils.py
invenio_app_rdm/theme/views.py
invenio_app_rdm/theme/views/__init__.py
invenio_app_rdm/theme/views/deposits.py
invenio_app_rdm/theme/views/filters.py
invenio_app_rdm/theme/views/general.py
invenio_app_rdm/theme/views/records.py
invenio_app_rdm/theme/views/records_ui.py
setup.py

closes #523 
Introduced a new configuration item for registering record serializers, e.g.:
```
APP_RDM_RECORD_EXPORTERS = {
"json": {
"name": "JSON",
"serializer": ("invenio_rdm_records.resources.serializers:"
"UIJSONSerializer")
}
}
```
The key is used for the lookup and should be URL-safe, while the `"name"` property is used for display purposes.
The `"serializer"` property is an import string for (or direct reference to) a factory function that can be called without arguments which creates an instance of the serializer (e.g. an argument-less constructor).
*Side note*: This configuration item is also used in the side-bar template, to only display links to export formats of registered serializers.
The URL to the export UI of a record can also be configured via a new configuration item …

523 export as json

---

invenio_app_rdm/config.py
invenio_app_rdm/theme/utils.py
invenio_app_rdm/theme/views/deposits.py
tests/test_utils.py

closes inveniosoftware/invenio-rdm-records#358
in the screenshot: default values for **rights** (licenses), **publisher**, and **publication_date** (via a callable).

deposit: add support for default values in the deposit form

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/creators.html
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less

closes #593
inveniosoftware/invenio-rdm-records#304 is still not resolved.
**screenshot**

bugfix: show affiliation btn only if affiliations

---

invenio_app_rdm/records_ui/views/__init__.py
invenio_app_rdm/records_ui/views/decorators.py
invenio_app_rdm/records_ui/views/records.py

hide those nasty `PIDDoesNotExistError`s and `PermissionDeniedError`s with their even nastier stack traces behind something more appropriate for users

records ui: add 404 page for permission and lookup errors

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/deposit.less

fixed - ```Deposit form: License dialog shows description on same line as title (should be next line) - note this was likely due to the fix done for putting "read more" link on same line as description.```

bugfix: licenses dialog description new line

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/625

user-reords-search: fix styling on empty results

---

invenio_app_rdm/config.py
tests/api/conftest.py
tests/api/test_protect_files_rest.py

- closes #577 
- Clearly they are protected, but not overriding the permission
factory leads to the same thing, so tests are not really convincing...

permissions: protect files-rest endpoints [+]

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/EditButton.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/NewVersionButton.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/recordManagement.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less

- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/683
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/684
- reduce DOM calls
- fix jump button bug (and others) by making semantic ui
javascript independent of presence of recordManagement
div (which could be absent if viewer is not owner)
Banner with newer version available, New Version button and error response displayed.
NOTE: 
- Because check on `can_manage` permission is done and this permission is not provided, the New Version Button will not show up by default for now.
- On the other hand, the "newer_version_exists" test has been set to True so that the "Newer version available" banner is always shown for now.

New Version available/button

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html

https://user-images.githubusercontent.com/24358501/112958168-7ca52980-9142-11eb-9ec9-ef1db2d87ae4.mov
closes #658 
- Add `defaultSortingOnEmptyQueryString` in search config
- Change the default sorting to newest in case the query string is left empty

search: Add defaultSortingOnEmptyQueryString in search config

---

invenio_app_rdm/records_ui/views/records.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareButton.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareModal.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less

closes #703
- Create a record
- As creator, you should be able to see the Share button
- Create an access link
- Visit `https://127.0.0.1:5000/api/records/<recid>/access/links` (API) to check if the access link has been created properly with the right permission
- Edit share mode (permission) and verify in the API.
- Delete link and verify in the API.
- One record can have multiple links (1:n), how should the UI reflect this? So far only accessing the element 0 of the list (emulating a 1:1 relationship).
- > Only one link initially......later we may have more.....
- The generated access links are the same for all the users? No reference to users when creating access links.

landing-page: share record access link modal

---

invenio_app_rdm/config.py
setup.py

* Changes local reference resolution from `https://localhost/schema`
to `local://` (closes inveniosoftware/invenio-rdm-records#356).
1. Checkout locally:
- https://github.com/inveniosoftware/invenio-rdm-records/pull/492
- https://github.com/inveniosoftware/invenio-vocabularies/pull/31
2. Create and run a new Invenio RDM instance
```
$ invenio-cli init rdm -c master
$ cd my-site
~/my-site/ $ invenio-cli install
~/my-site/ $ invenio-cli packages install ../invenio-rdm-records ../invenio-vocabularies ../invenio-app-rdm
~/my-site/ $ invenio-cli services setup
~/my-site/ $ invenio-cli run
```
Working locally ✅

records: change JSONSchema resolution

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/search.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less

* Includes search results, user search results, and record landing pages.
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/667.
Depends on:
- https://github.com/inveniosoftware/invenio-rdm-records/pull/499 (backend implementation)
- https://github.com/inveniosoftware/invenio-records/pull/252 (adds needed hooks to record base api)
- https://github.com/inveniosoftware/invenio-records-resources/pull/233 (adds access status to service schema dump so it is accessible in the UI serialisers)
**Status**
Mostly done see screen recordings.
https://user-images.githubusercontent.com/9035606/114845595-30154b80-9ddc-11eb-9459-02e62861510b.mov
https://user-images.githubusercontent.com/9035606/114845605-33103c00-9ddc-11eb-8d9b-1d5db57e09bd.mov
**Missing**
- Move `AccessStatusEnum` to a …

global: access status label on search and landing pages

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/export.html
invenio_app_rdm/records_ui/views/records.py

* Back to edit button only available
if user has edit permissions
* Updated message if previewing a
published record without a draft
* Version banner is only displaying if
we are not previewing the latest version
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/909

preview: Bug fixes

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html

- requires https://github.com/inveniosoftware/react-invenio-deposit/pull/332
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/944
Issues:
- The error messages on the form are temporarily shown.
- When `back to edit` those error messages disappear, the user would need to `save` again to see them.
- The citation box is broken (there is another issue to tackle that)
https://user-images.githubusercontent.com/6756943/125286410-0f498d00-e31c-11eb-867e-b0ede19eb559.mov
Note the `if`s added to the Jinja template are not ideal. But this will need to be changed in any case when creating the new content types that will allow us to version before the LTS.

records_ui: fix detail template to not require any value

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/description.html

- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/726
Tests have been added at RDM-Records level.
The ` sanitize_html` Jinja filter is not needed since the service schema already sanitizes it, therefore we avoid the double sanitization which ends in tags removal. [Reference](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/schemas/metadata.py#L394)

templates: render html tags in landing page descriptions

---

invenio_app_rdm/config.py
tests/conftest.py

- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/953
Uses bare JSONSerializer from Flask-Resources
The description shows the HTML tags. I think this is correct?
```
"description": "<h2>&lt;h1&gt;Normal description&lt;/h1&gt;</h2><p><strong>this should be bold</strong></p>"
```
**Open Question**
Why does the UISerializer not use MarshmallowJSONSerializer as parent since it is anyway defining a scheme? Logic could be simplified to add the UI key with Marshmallow schemes.

exports: json should not use ui serializer

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less

did not use the existing class - since it's used other places - just to be sure we are not creating any other bug.
closes #957 
**screenshot**

styling: fix txt and img alignment

---

.gitignore
invenio_app_rdm/records_ui/views/deposits.py
tests/conftest.py
tests/ui/test_deposits.py

'correctly' means:
- with translation
- still relying on cache
- by using parent entry title if need be
(not relying on `subtype_name` and `type_name` anymore)
also:
- refactors vocabularies dumping for deposit page
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/785

ui: label resource types correctly [+]

---

invenio_app_rdm/config.py

- requires https://github.com/inveniosoftware/invenio-rdm-records/pull/793
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1044
Example run:
```
[2021-08-04 10:26:15,303: INFO/MainProcess] Received task: invenio_drafts_resources.services.records.tasks.cleanup_drafts[722ee3f8-4694-4b92-a2ad-774f2e2c451c]
[2021-08-04 10:26:15,474: INFO/ForkPoolWorker-9] Task invenio_drafts_resources.services.records.tasks.cleanup_drafts[722ee3f8-4694-4b92-a2ad-774f2e2c451c] succeeded in 0.0647518379999994s: None
/Users/ppanero/.virtualenvs/cleanup_drafts/lib/python3.7/site-packages/marshmallow/fields.py:221: RemovedInMarshmallow4Warning: Passing field metadata as a keyword arg is deprecated. Use the explicit `metadata=...` argument instead.
RemovedInMarshmallow4Warning,
[2021-08-04 …
```

config: fix drafts cleanup task

---

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/frontpage.html

All links are working in the frontpage.

templates: replace deploy by run

---

setup.py

Adds logging with sentry-sdk extra. It is not configured by default.
Tested with a new instance (v6.0) from scratch and no errors were shown. 
**Open questions**
- Do we want to add sentry to the docker-compose file? It would **not** be a zero-config thing, because the teams/users/project/dsn would still need to be created by the user
- Should docs be added somewhere in InvenioRDM or the Invenio ones are enough (those are the ones I followed).

dependencies: add invenio-logging with sentry sdk

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js

https://www.w3.org/TR/WCAG20/#minimize-error-cues
From NYU's a11y review - 
The toggle switch (checkbox) to turn on/off "All Versions" does not have a for/id association with the label/input.
Consider:
```
<div class="ui toggle checkbox">
<input class="hidden" readonly="" tabindex="0" type="checkbox" value="" name="versions-toggle" id="versions-toggle">
<label for="versions-toggle">View all versions</label>
</div>
```

a11y: Add name and id to the "Versions" toggle

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html

Iframes should have a title attribute, "to describe the contents of each frame. This provides a label for the frame so users can determine which frame to enter and explore in detail. "
see: https://www.w3.org/WAI/GL/WCAG20-TECHS/H64.html

A11y: iframe gets a title attribute

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/citation.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/contributors.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/description.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/doi.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/licenses.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/subjects.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_records_search/components.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/footer.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/frontpage.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/search.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/message.variables
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/frontpage.html

This PR address 3 Accessibility issues:
- Some of the colors used are a bit too low-contrast. They are bumped up to at least 4.5:1.
- Semantic markup: some "Landmarks" are added. Also more headings tags (h2, mainly.) 
- For search results, instead of the whole item being linked, just the title is.  (Also, for this to work, the authors links needed to be updated.)

A11y colors and results links

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/export.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/metrics.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/versions.html

Updating markup to meet requirements:
- `<dt>` and `<dd>` elements must be contained by a `<dl>`
-- https://dequeuniversity.com/rules/axe/4.3/dlitem
- `<dl>` elements must only directly contain properly-ordered `<dt>` and `<dd>`groups, `<script>`, or `<template>` elements
-- https://dequeuniversity.com/rules/axe/4.3/definition-list

A11y: markup for definition lists

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/subjects.html
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less

Closes #1226
Linked subjects to search result page for the respective subject
__Screenshots__
__Hover state__

landing page: link subjects to search results

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/footer.less
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/footer.html

Closes #1271
Changed header level from `h4` to `h2.ui.small.header`
__Screenshot__

footer: change footer headings-level

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html

Closes #1232
Added links to identifiers with url, using the `pid_url` filter from `invenio_app_rdm/records_ui/views/filters.py`.

landing page: add links for identifiers

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/CopyButton.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareButton.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareModal.js

Closes #848
__ShareModal__
- Added copy functionality to "Get link"-button.
- Added popup on click (this is also showing when clicking the "Get link" button).
- Added cleanups for async functions in useEffect functions
- Made the dropdown more screen-reader friendly by adding `selectOnNavigation={false}`
I also made some accessibility improvement for the existing __CopyButton__-component:
- Merged the two popups into one, to avoid the need to click twice (on keyboard) to get the "Copied"-feedback.
- Added alert-role to announce the copied-message to screen readers (in the CopyButton this could be added directly on the Popup-component, as the content is changing when hovering/clicking).
I was considering to use the existing CopyButton in the ShareModal and adjust it to be more flexible: 
- …

share-modal: copy on get link

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/dashboard.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/deposit.html
invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/index.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/index.js
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
invenio_app_rdm/theme/views.py

Hide communities from dashboard.
Hide requests from dashboard.
Ensure is properly redirected when trying to access hidden content.
Hide selected community from deposit form.
Move the requests notifications link responsability to invenio-communities.
closes inveniosoftware/invenio-app-rdm#1268

Communities: hide content when communities are not enabled.

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/uploads.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less

Closes #251
- Redesigned the no-results page-component
- Added clear-selection button to facet headers
- Added header to help-links
__Changes from initial mockup__
- Replaced the additional search bar with "start over"-button
- Moved search icon from above the header to the "start over"-button, as it looked a bit messy (imo), especially on the uploads-page
__Note:__ The semantic-ui padding setting in the segment is not functioning, most likely because the `.ui.segment.secondary`-class is overwritten in invenio-theme. This can be solved by adding the default setting to the overrides-file (which should be done, rather than adding more custom css).
__No results for search term__
__No search term__
__Updated sidebar__
__Uploads page__

search: redesign no-results page and add clear facets button

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js

Closes  #1114
- Uses `updateQueryState` in the frontend to clear facets when searching for a new term

search: clear facets on new search term

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareModal.js

Related to #1318 
- Copy on get-link now works for Chrome, but Safari still has the same issues likely because of async issues due to the creation of the link...

landing page: fix bug where get-link button doesnt copy

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less

Closes #1316
- Added disabled state to clear-facets button if none selected
- Center aligned heading & clear-facets button
- a11y: Added heading level to Card headings and removed `!important` rule from css

search: add disabled state and align clear-facets button

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/licenses.html
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page/licenses.less

- Changed licenses-title to "Rights"
- Made all licenses clickable for consistency

landing page: make all licenses clickable

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/dashboard.html
invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/index.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/tab.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/tab.variables
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm_requests/theme.less
invenio_app_rdm/theme/templates/semantic-ui/invenio_requests/community-submission/index.html
invenio_app_rdm/theme/webpack.py

Change the UI of the dashboard with the feedback received.
Display username instead of email and avoid hard coded organization. 
closes: inveniosoftware/invenio-app-rdm#1245
Temporarily renamed header:

Dashboard: improve UI

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page.less

Closes #1093
- Removed link to all versions if total versions < 1.
- Converted the version-list from semantic ui `Grid` to `List`.
- Disabled link for current version (it was only linking to itself).
- Changed the muted text-color when on background to avoid color contrast issues.

landing page: remove all versions-link if < 1, disable link if current

---

.github/workflows/tests.yml
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page/creatibutors.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/variables.less

* moves Icon after name for both landing page and search results
* standardizes the color of the linked names
* standardizes html classes for landing page and search results so they can be styled together
* closes #1161

Make ORCID icons larger and swap order

---

invenio_app_rdm/upgrade_scripts/migrate_7_0_to_8_0.py

Migration script for v7 -> v8 which updates the `icon` property of license vocabularies

upgrade: add migration script for v7 -> v8

---

invenio_app_rdm/config.py
invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js

Add config variable to set upload quota on deposit form.
closes #1160 
**Reminder**
2. You agree that …

config: add deposit form quota config

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/manage_menu.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/theme.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides

Closes #1347 
- Moved the admin-section out of the details section on mobile.
- Added a manage button on top of the page for mobile and tablet, to trigger a popup with the buttons
- Also fixed some spacing inconsistencies for the admin-box on desktop
__Desktop__
__Tablet__ 
__Mobile__

landing page: move manage record section for mobile

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/components/base.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/index.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides

**Needs [react-invenio-forms PR 118](https://github.com/inveniosoftware/react-invenio-forms/pull/118)**
Solves the responsibility issues for the My dashboard page of #1360. Search result page issues are solved in `invenio-search-ui` [PR #129](https://github.com/inveniosoftware/invenio-search-ui/pull/129).
- Changed the column width of the tab content to be full grid-width for mobile and tablet.
- Moved the facet filter to a slide-in sidebar triggered by a filter button for mobile and tablet.
- The desktop version remains the same as before.
The sidebar closes when clicking the close-button or by clicking outside the sidebar.
Accessibility was tested with axe DevTools and VoiceOver.
__Filter closed__
__Filter open__
__Filter closed__
__Filter open__

my dashboard: add responsive layout

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_login.html

Closes #1281
- Changed the global account-menu to be dropdown-only, not link + dropdown as before.
- Added aria-attributes for a11y
- Added keyboard accessibility
- Tested with VoiceOver & axe DevTools

header login: add a11y to profile menu

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/citation.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.overrides

landing page: fix styling for citation section

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js

Fixes an issue where the component `RDMRecordSearchBarElement` is trying to execute a function `executeSearch` which is undefined. This property is not being injected anymore by `react-searchkit`'s `SearchBar` component.

RDM search bar  undefined prop 'executeSearch'

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/subjects.html
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/label.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/list.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1461
- Changed colors of the subject labels
- Changed the list from `dl` to `ul` for a11y purposes.

landing page: update subject list a11y and styling

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html

Closes #1451
Added class needed to activate the tab menu on the landing page.

landing page: add missing class to tab menu

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/header.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1486
- Removed the hidden-class from `site.overrides` and applied it only to the `h3` header in the sidebar.
- The hidden-class was added in this commit https://github.com/inveniosoftware/invenio-app-rdm/commit/d71ca9d52f0cb12d37a16bb46f03b6314238f96a , just 5 days ago, so unlikely it's used anywhere else.

remove hidden-class from global overrides

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/manage_menu.html
invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js

* enable community curator to access deposit form
of the draft submitted for community review and
curate the record
* remove delete button in draft deposit
(community curator only)
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1485
USER view of the request record preview:
USER view of the deposit form of the submitted draft
community curator view: deposit form of a draft submitted for review
community curator view: request record preview

deposit: add draft curation button

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides

Make stackable menu span full width on mobile.

container: override width for stackable menu

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_login.html

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1196
- It was necessary to separate the burger-button and the close-menu-button to ensure good accessibility
- Added aria-attributes
- Changed the burger-button from checkbox to button as the label-solution with `role="button"` did not work properly with the screenreader.
- Added click-handlers (also triggered by keyboard because of `<button>`)

Burger menu: add accessibility

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1468
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1469
Swapped the community header and preview header, and aligned back-button.

Swap preview and community header

---

invenio_app_rdm/config.py

- requires https://github.com/inveniosoftware/invenio-records-resources/pull/331
- closes https://github.com/inveniosoftware/invenio-communities/issues/584
https://user-images.githubusercontent.com/6756943/166913355-0745d4a3-b835-4d8f-9bbd-b8f9cae6ac54.mov
Working with redis and rabbitmq, can be seen the queue/key is there and then dissapears after it's consumed.

config: add indexer to celery beat

---

invenio_app_rdm/config.py
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html
invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js

Usually (but not necessarily), the back-end specifies file sizes and their limits in binary format (i.e. powers of 1024: KiB, MiB, GiB) rather than decimal format (i.e. powers of 1000: KB, MB, GB).
Until now, the front-end simply calculated file sizes in decimal format, which *could* be incongruent with the specification in the back-end.
This PR introduces a new configuration variable that allows switching between the formats, to enable sticking to the same format.
Decimal format:
vs. binary format (same file size limit):
Requires https://github.com/inveniosoftware/react-invenio-deposit/pull/467
If you've added [third-party code (copy/pasted or …

Files: add option to display file sizes in binary or decimal units

---

invenio_app_rdm/records_ui/views/deposits.py
tests/ui/test_deposits.py

- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1516
Since all the occurrences happen at _views_ level it is accepted to access the `g` object. The `current_user` does not provide an identity (it provides `id` and `roles`) and we would need to build the identity from it, which is already stored in `g.identity`.

views: remove usage of system_identity to query vocabularies

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/message.overrides

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1524
Added padding to preview header in request details record tab.

request record preview header: add missing spacing

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/card.overrides

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1525
**Needs PR** https://github.com/inveniosoftware/invenio-communities/pull/644
- Added card container and headline to all `<SearchHelpLinks />` for it to be consistent with the `<BucketAggregationElement />`. 
- Put header and content in the same `<Card.Content>` in all `.rdm-facet-container`s to gather related content and reduce spacing between heading and content.
- Added same logic to all `Clear facets` buttons (only visible if facets selected).

facets-sidebar: fix inconsistencies in layout

---

invenio_app_rdm/requests_ui/views/requests.py

record tab was being hidden if the request was closed, for everyone. Now keeps it visible if is your own request, otherwise still hidden.
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1521

request details: show preview if user own request

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/accordion.overrides

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1547
**Related PR** https://github.com/inveniosoftware/invenio-communities/pull/656
- Changed the arrow icon to `<Button/>` to ensure that the icon is accessible by keyboard and with a screen reader. 
- Added `:not(.button)` to the `.ui.accordion .active.title .icon`-override as both the button `<button>` and the icon `<i>` get the class `.icon` when using the SUI icon-button, meaning the arrow is rotated 2x90 deg.
Tested with VoiceOver on Mac.

parent facet value: change arrow icon to button for a11y

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides

Now wraps to show the whole title instead of overflowing out of the layout
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1568
before:
after:

record details: fix title overflowing if too long

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides

Moved the `.inline-computer`-class to `site.overrides` as this can be useful for other elements than `.item.meta` only.
Needed for https://github.com/inveniosoftware/invenio-communities/pull/663

move inline-computer class to site.overrides

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js

Closes https://github.com/inveniosoftware/invenio-theme/issues/286
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1577
- Add `.trigger` to all accordion panels.
- Removed accordion init function -> moved to invenio-theme https://github.com/inveniosoftware/invenio-theme/pull/284
- Changed the carret to be left pointing when closed, down when open

theme: move accordion init function to invenio-theme

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1582
- Adds spacing to funding list item label
- Fixes a bug in the files-section markup

landing page: funding spacing and layout bugs

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1578
Keeps the license item a row, to be aligned with the radio button also on mobile.

item: keep license item flex row on mobile

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides

Before:
After:
Screenshots of portrait format.

Logo: avoid logo image overflowing

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js

now correctly holds the filter state while switching between open/closed and also when doing an empty search
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1690

dashboard requests: correct searchbar behaviour

---

invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareModal.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js

Refs https://github.com/inveniosoftware/invenio-app-rdm/issues/1707
Note: components.js will need some more fixes later.

i18n: Fixes strings marked for translation.

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1731
- Replaced `rm-pt` with `pt-0`

landing page: remove excessive spacing from files table

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_login.html

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1726
- Added breakpoint rule to the tablet-class
- Added `.mobile.tablet.only`-classes as `.mobile.only` and `.tablet.only` was causing conflicts when combined. 
- Updated visibility classes on the global menu.

burger menu: combine mobile and tablet visibility class

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1733
Added `overflow: hidden` to preview accordion-panel, as the `#document` in the iframe was overflowing by 2px.

landing page: prevent iframe in preview to overflow

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html
invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1734
**Funders list on landing page:** 
- Updated the markup for a11y purposes
- Updated styling to follow the same style as the other lists in "Additional details"
**Tab menus:** Discovered inconsistencies in id-names across tab-menus, causing the aria-labels to not update correctly: Updated id-names to follow the same structure in all tab menus, and updated the a11y function accordingly
Tested with VoiceOver on Mac.

landing page: update funders list styling & fix tab a11y bug

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides

Fixes the community header mis-alignments introduced in this PR https://github.com/inveniosoftware/invenio-app-rdm/pull/1710

community header: fix alignment

---

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1748
- Added spacing to search bar (does not affect mobile version)

header: add right margin to search bar

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/icon.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.overrides

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1714
The issue was that the dropdown container width was adjusting when the icon rendered. E.g. when the icon was rendered, the dropdown container shrinked.
This fix reserves space for the success/error icon by creating a `div`. Does not reduce the dropdown size a lot and it's enough to make the whole cell static when changing the selection.

members: reserves space for success/error icon

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page/creatibutors.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1736
- Added separator class to creatibutors-component in `SearchItemCreators` (to keep same markup in both places).
- Had to specify `.ui.items > .item .meta .creatibutors` for the styling to be preferred over default styling in the search-results case.
- Added spacing to separator class

creatibutors: add spacing between icon and separator

---

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html

This adds an Aria-label to the inbox link, because the text label is hidden in desktop view.
It also adds an empty alt tag to the user avatar, since we don't have any descriptive info about that image.
This closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1678

A11y: Inbox icon aria label; avatar image alt tag

---

setup.cfg

**Warning** this means that these 2 commits will be in:
* https://github.com/inveniosoftware/invenio-assets/commit/b89bf81c04daa09d95a368eb6cddb5bdd592a06e
* https://github.com/inveniosoftware/invenio-assets/commit/70d37ebecd46ca9cdc6e9fbe15c5dfd0b24ae6f2
I wouldn't release this in a InvenioRDM `v9.1.x`, I would go for `v9.2` or `v10`. If merged to `master`, then we need to pay attention to future releases.

bump invenio-assets

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities_items/MobileCommunitiesItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests_items/ComputerTabletRequestsItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests_items/MobileRequestsItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/ComputerTabletUploadsItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/MobileUploadsItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js

Remove empty content.
Create a custom mobile interface.
Fix request_items naming.
closes: #1771
Computer:
Tablet:
Mobile:

Dashboard uploads: refactor uploads view

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/ComputerTabletUploadsItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/MobileUploadsItem.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page/creatibutors.less
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/dropdown.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides

- Added labeled button to tablet/desktop
- Moved buttons to dropdown on mobile
- Cleaned up some inconsistent spacing
- Removed excess right-spacing on last items on centered content causing the content to not be completely centered
- Removed excess bottom spacing on the item
- Added spacing below creatibutors to separate the content slightly, and to make sure the creatibutors are not squished together when stacked on the smallest screens
- Removed `margin-auto` on each creatibutor item, changed the creatibutor-wrap to be `inline-flex` and removed `flex` from the container to make sure the content follows the text-alignment.
- Added spacing between the icon and the headline

dashboard uploads: change buttons to dropdown on mobile

---

invenio_app_rdm/upgrade_scripts/fix_migrated_records_from_8_0_to_9_0.py

Adds migration for parent communities for older records.
**Reminder** …

migration: add migration for parent communities

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js

This provides an `alt` to identity icons (e.g. ORCID) to solve the following accessibility issue:

icons: add alt value for accessibility link requirement

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/input.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.variables

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1925
- Removed hardcoded color for search icon
- Removed color-specification for search-button
The `@searchButtonColor` variable is already defined in `button.variables` and the color is set in `button.overrides`, so the removed css should not be needed (and does not seem to make any difference when testing). 
**The reason for this change is that the mentioned css made it difficult to override the colors in the local instance.**
Related to https://github.com/zenodo/zenodo-rdm/pull/54

theme: remove hardcoded override of search button color

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides

The text on the "forgot password" page is invisible due to white text on white background due to `color: @white` on `.cover-page`, see screenshot:
This PR sets the text color to muted on white segments:

theme: makes sure text on white segments is visible

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page/creatibutors.less

For some reason, the title for the contributors-group is no longer aligned with the contributor names, and it looks a bit messy. See screenshot:
This PR makes it so that the list looks like in the following screenshot:

creatibutors: align contributor title with contributors

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/subjects.html

The subject links a record landing page weren't scoped to the scheme. This resulted in being redirected to a search that wasn't specific to the subject clicked on e.g., clicking on LCNAF subject "Saguenay River (Québec)" would lead to a search picking up records that have "Saguenay River (Québec)" as a keyword. Really we encounter the issue when 2 vocabularies have same subjects (e.g., MeSH and LCSH crossovers).
Here we fix the scoping issue by using the `id` in the search. We could have used `<scheme> AND <subject>` :shrug: .

link to subject id search from landing page (fix)

---

invenio_app_rdm/cli.py

This PR introduces a new CLI command for calling `service.rebuild_index()` for every service with this method registered in the service registry (which should include all relevant services in the latest releases).

CLI command for rebuilding the search indices

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/frontpage/RecordsList.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js

Closes https://github.com/zenodo/zenodo-rdm/issues/163

error messages: align home- and search page

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities_items/ComputerTabletCommunitiesItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities_items/MobileCommunitiesItem.js

* community list url now redirects to /communities/*slug* instead of /communities/*id*
* closes https://github.com/inveniosoftware/invenio-communities/issues/882

url: redirects to slug not id

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides

Needed in https://github.com/inveniosoftware/invenio-communities/pull/884
The vertical SUI menu is currently only good for two elements (`width: 15em`). Instead I set a min-width on the item itself (so it can still expand), and added `width: max-content` to the menu.
Also fixed some excess/missing borders for the smaller screens version.

theme menu: fit  more than two items in horizonttal mobile version

---

invenio_app_rdm/__init__.py
invenio_app_rdm/communities_ui/views/ui.py
invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/theme/views.py
invenio_app_rdm/users_ui/views/ui.py
setup.cfg

- NOTE: Flask-Security-Invenio invenio-accounts invenio-admin invenio-administration invenio-communities invenio-drafts-resources invenio-files-rest invenio-formatter invenio-i18n invenio-oaiserver invenio-oauth2server invenio-oauthclient invenio-pidstore invenio-previewer invenio-rdm-records invenio-records invenio-records-resources invenio-records-rest invenio-requests invenio-search-ui invenio-theme invenio-userprofiles invenio-users-resources invenio-vocabularies all other packages needs to be released first

migrate: flask_babelex replaced by invenio_i18n

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html

Missing header on files when restricted, see image

details: fix missing files header

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/form.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/image.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/card.overrides

Closes https://github.com/inveniosoftware/invenio-communities/issues/907
This PR makes the horizontal tablet menu (e.g. in community settings) span the full width.

menu: make horizontal menu full width on tablet

---

invenio_app_rdm/config.py
invenio_app_rdm/records_ui/views/records.py

This PR fixes the tests on the master branch, here's the details:
The problem is caused by the export page [simply passing hard-coded JSON formatting arguments](https://github.com/inveniosoftware/invenio-rdm-records/pull/1266) to all serializers, no matter which arguments they accept.
This isn't accepted by the code path along the Dublin Core XML serializer and causes a failure (more details in the RDM-Records PR linked below).
In this PR, I make the arguments to be used configurable per serializer.
This obviously makes the export serialization more flexible (e.g. it enables users to set custom indentation for JSON, ...) and is actually required to enable configuration of the DC XML export (UI) to behave like before its update.
I've opened up a complementary PR in RDM-Records, which …

Exporters: make serializer parameters configurable

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides

Closes https://github.com/inveniosoftware/invenio-communities/issues/950
This PR adds a media query to the `.extra`-class to remove absolute positioning on mobile, plus removes the bottom margin from the heading to make the spacing consistent.

community-item: Fix styling bug for mobile item

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/theme.less

* this bug prevented the migration to webpack 5, because this line was
translated to a relative path, which could not be converted to an
absolute path. this is bad, because webpack 5 introduced a check about
relative paths and removed those and printed an error.

fix: untranslatable relative path

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides

* closes https://github.com/zenodo/who-rdm/issues/70
This was added in [this PR](https://github.com/inveniosoftware/invenio-app-rdm/pull/2185#discussion_r1184928414) but since we cannot identify/test for what elements it was meant to fix we just revert it as the ones that break are quite prominent.

theme: remove outline

---

invenio_app_rdm/records_ui/views/__init__.py
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/icon.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/transition.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides
invenio_app_rdm/theme/views.py

addresses https://github.com/inveniosoftware/invenio-communities/issues/874
See screen recording at https://github.com/inveniosoftware/invenio-communities/pull/966

frontpage: rewrite communities carousel to python and jinja

---

invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html

* no longer shows None when neither full_name or user_name are set
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2229

ui : fixing username not appearing

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/doi.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/details.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/segment.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides

Closes https://github.com/zenodo/zenodo-rdm/issues/405
Fixes some inconsistent spacing & replaces the "no communities" message with a small note instead.

sidebar: improve spacing and change no-communities message layout

---

invenio_app_rdm/config.py

This PR has been split into three different PRs, more details are available in the [comment below](https://github.com/inveniosoftware/invenio-app-rdm/pull/2242#issuecomment-1623505671).
This PR requires https://github.com/inveniosoftware/invenio-rdm-records/pull/1306 to work.
It provides a UI for the access requests detail pages, as well as a button for requesting access from restricted records' landing pages.
* UI for the guest-based access requests
* New share modal according to the RFC
* Management of access grants
* Management of secret links
* Management of record access settings
Users should be able to remove access grants that give themselves access to the record (i.e. where the current user is the subject), but the UI should warn them beforehand ("are you _really_ sure? this might …

Permissions for access requests

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/access-form.html
invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/guest-access-request/index.html
invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/user-access-request/index.html
invenio_app_rdm/requests_ui/views/requests.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/accessForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js
invenio_app_rdm/theme/webpack.py

This PR provides the front-end part for the [access requests](https://github.com/inveniosoftware/invenio-rdm-records/pull/1306).
It introduces a form on the landing pages of records with restricted files that can be used by users or guests to request access.
https://github.com/inveniosoftware/invenio-app-rdm/assets/15194802/47bd8d90-8baa-4b0a-b1d5-e80ff4830fe6
https://github.com/inveniosoftware/invenio-app-rdm/assets/15194802/9e9bf71d-bd52-4f6a-9134-0ccadf09622e
Note that the guest is, per definition, not logged in.
As such, there _is no_ dashboard for the guest, and the usual tabbed header of the request detail page is missing.

Record landing pages: access request forms

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/image.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html

Closes https://github.com/zenodo/zenodo-rdm/issues/409
Fixes
- alignment issues for community headers.
- responsive breakpoints (they were causing a point where some elements were not visible at all, due to some px difference in the variables).

community headers: fix alignments and logo-sizing of community headers

---

invenio_app_rdm/records_ui/views/records.py

* Depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/1370.
* Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1282.
* Redirects for fetching latest versions or resolving DOIs should be
using the "302 "Temporary Redirect" status, since the redirecting URL
might change in the future.

views: fix redirect codes to 302

---

invenio_app_rdm/config.py
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/doi.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/details.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/doi.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/header.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/list.overrides
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/versioning.en.html
invenio_app_rdm/theme/views.py

parent-doi: add link to record landing page

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html

* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1374
Case 1: `accept_conditions_text = null` or absent
Case 2: `accept_conditions_text = "Buy me a unicorn"`
Case 3: `accept_conditions_text = "<h1>Buy me a unicorn</h1>"`
Case 4: `allow_user_requests` or `allow_guest_requests` is set to false:

ui: render access request form based on settings

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/button.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides

Closes https://github.com/inveniosoftware/invenio-communities/issues/983
Fixes the alignment in the members column:

theme item: Fix align-no-checkbox bug

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/CompactStats.js

closes https://github.com/zenodo/rdm-project/issues/199
Change stats label from `unique` to `total`
**Reminder** …

ui: change stats label from unique to total

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/PendingCommunitiesModal/PendingCommunitiesModal.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/PendingCommunitiesModal/PendingCommunitiesSearch.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesListModal.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesListModal/RecordCommunitiesSearch.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/image.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/modal.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides

Closes https://github.com/zenodo/rdm-project/issues/171
Aligns the layout of all community modals, and fixes the community list view in the sidebar for mobile.
Mobile:

community modals: align modal layouts

---

invenio_app_rdm/records_ui/views/decorators.py

* allows to pass the parent id and returns the latest version
* requires https://github.com/inveniosoftware/invenio-drafts-resources/pull/240
* closes https://github.com/zenodo/rdm-project/issues/174

decorator: updates pass_record_or_draft

---

invenio_app_rdm/config.py
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/citations.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/manage_menu.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/technical_metadata.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/grid.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/menu.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/message.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/segment.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/accordion.overrides

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2315, closes https://github.com/zenodo/rdm-project/issues/200, closes https://github.com/zenodo/rdm-project/issues/191, closes https://github.com/zenodo/rdm-project/issues/198
- Moves citations to the sidebar
- Fixes "Additional details" visibility bug
- Moves "Created" and "Modified" date info from main column to "Technical metadata" in the sidebar
- Removes top margin from banners
- Removes community list if no communities and not record owner
- Fixes a11y for metadata labels

landing page: make changes according to task list in related task

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html

Landing page jump to top button: 
- Fixes a small but annoying bug where clicking the entire button container (full width) triggers the jump-to-top event. Moves the trigger class to the actual button.

jump to top button: move event to button only

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/theme.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header_login.html

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2374
- Fixes all errors detected in the global header
- Removes duplicate preview id's from landing page, not needed
- Tested with VoiceOver in Safari & axeDevTools
- No visible changes in the UI

address accessibility errors on global header and landing page

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html
invenio_app_rdm/records_ui/views/decorators.py
invenio_app_rdm/records_ui/views/records.py

* use can_media_read_files permission to display media files box
* fix ui depending on permissions logic
* closes https://github.com/zenodo/rdm-project/issues/219
Different cases depending on permissions:
1. Record is public:
1.1 media files present:
1.2 no media files - no box
2. Record is public, but files are restricted:
2.1 Record owner view:
no media files - no box
2.2 Guest view:
no media files - no box
3. Record is fully restricted:
2.1 Record owner view:
no media files - no box
2.2 Guest or another user view - no landing page view - redirect to login or permission denied page
UPD: Preview button is absent from media files (draft and record views)

media files: fix permissions and ui

---

invenio_app_rdm/config.py
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/locations.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/locations.html

closes https://github.com/zenodo/rdm-project/issues/228
Location features have 4 attributes: `place`, `geometry`, `description` and `identifiers`. 
Therefore, 4 possible renders were identified:
- Place (Geometry)
- Place
- (Geometry) 
- Unknown 
Optionally, the description is added below the rendered place/geometry
Result:

records: added locations field to landing page.

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/creatibutors.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/description.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/files.html
invenio_app_rdm/records_ui/views/__init__.py
invenio_app_rdm/records_ui/views/filters.py
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/header.overrides
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides

Closes https://github.com/zenodo/rdm-project/issues/229
- Removes "Description" header from the UI (the element remains in the DOM but with a new `sr-only` class, to keep it available for screen readers.
- Changes Additional Details view from tabs to list (accordion if sub content longer than 5 items)
- The accordion is open by default
- Improves accessibility for all files accordions
- Custom fields are linked to search for namespace terms
- External url added for namespace docs
- Added "Notes" description to warning message box
- Added acronym to awards

landing page: improve a11y for accordions, change add details view

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2352
Replaces the id by aria-label so that the label gets disconnected and the aria-label is used instead. This resolves errors related to duplicate ids due to the responsive sidebar.

versions toggle: replace id by aria label

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html

Fixes the following issue:
The divider for `metadata.references` was not within the related conditional.
After fix:

landing page: move divider within conditional

---

invenio_app_rdm/config.py

Fixes community error when trying to restrict a community with public records

communities: fix unhandled visibility error

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/creatibutors.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html
invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/macros/request_header.html
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/landing_page/creatibutors.less

Closes https://github.com/inveniosoftware/invenio-requests/issues/362
- Converts creatibutors list to `ul` instead of `dl` due to accessibility errors.
- Adds `sr-only` headlines to creators and contributors on the landing page
- Reduces whitespace on creatibutors, otherwise the UI remains the same.

creatibutors: fix semantic html

---

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2333
Comment: I removed the `and loop.depth == 0` from the conditional, as it was preventing the active state to show. (The actual depth == 1.) I'm not sure I understand why it should be there, so if it should for some reason, please let me know.

header: add active status to menu items

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/input.overrides

* closes https://github.com/zenodo/rdm-project/issues/244
Before:
After:

css overrides: cancel the influence of accordion errors on its input placeholder

---

invenio_app_rdm/communities_ui/views/communities.py
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/manage_menu.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/tombstone.html
invenio_app_rdm/records_ui/views/records.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ManageButton.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js

* closes https://github.com/zenodo/rdm-project/issues/262

navbar: add cog menu

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/AccessRequestForm.js

Closes https://github.com/zenodo/rdm-project/issues/373
Yup's object validation: [string.required](https://github.com/jquense/yup#stringrequiredmessage-string--function-schema) doesn't allow empty strings 
Full names can be null or empty strings. We added a check in place in https://github.com/inveniosoftware/invenio-app-rdm/pull/2490 to convert any null values to empty strings which made this validation fail always and the form stopped working.

ui: landing_page: access form: make full name not required

---

invenio_app_rdm/records_ui/views/filters.py

* closes https://github.com/zenodo/rdm-project/issues/360
**Note: applies also for media files for both zenodo and rdm**
No default preview - preview the first file:
Default preview is set:

landing page: sort files alphabetically

---

invenio_app_rdm/records_ui/views/records.py

* closes https://github.com/zenodo/rdm-project/issues/392
The flow for records: on render of landing page, if `record.access.settings` are empty, they are getting prefilled with default values. **Not saved to db yet**. In case of user managing settings and clicking the "Save" button - all the data get's sent to the db.
The flow for drafts: settings are getting populated on publish of a draft even without this fix

access settings: populate parent with default settings if not present

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessRequests/AccessRequestsTab.js

* closes https://github.com/zenodo/rdm-project/issues/406
Before:
After:
Editor:
Result - saved as HTML and displayed:

access request: make accept conditions field an editor-like

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/details.html

Closes https://github.com/zenodo/rdm-project/issues/446
I tested adding the subjects to the "Keywords and Subjects" block in the sidebar, as proposed in the task, but I'm not sure it makes sense due to the different types of information that can be displayed. For some of the data, it could work well to add it there (e.g. actual subject data with a URL to the term docs), but for other data, like ISSN, it doesn't really make sense? For this reason, I added it to the "Additional details" section, which is also not the best solution for all the data, but it allows for more context. 
See the screenshots below, and let me know if anything should be done differently.

landing page: add extras block to additional details template

---

invenio_app_rdm/config.py

Fixes https://github.com/zenodo/rdm-project/issues/565
The config set fetcher didn't evaluate the sets rather, tried to fetch it from the record.
Having same method names for [evaluation](https://github.com/inveniosoftware/invenio-oaiserver/blob/f2cfe79138b96864f393281fbbb818e08f1e9b89/invenio_oaiserver/ext.py#L42) and [fetcher/getter](https://github.com/inveniosoftware/invenio-oaiserver/blob/f2cfe79138b96864f393281fbbb818e08f1e9b89/invenio_oaiserver/utils.py#L183) might have been the cause for confusion between those.
The new config method is referred from oaiserver [config](https://github.com/inveniosoftware/invenio-oaiserver/blob/f2cfe79138b96864f393281fbbb818e08f1e9b89/invenio_oaiserver/config.py#L130)

config: update OAISERVER_RECORD_SETS_FETCHER to correct set fetcher

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/SetQuotaAction.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/SetQuotaForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RecordActions.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/SearchResultItemLayout.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/users/UserActions.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/modules/modal.overrides

Closes https://github.com/zenodo/rdm-project/issues/500 
- UI improvements (default input in GB, toggle to use bytes), more info displayed in modals.
- Updating apiUrl for record drafts.

UserActions: Fix wrong endpoint for drafts + UI improvements

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html

* closes https://github.com/zenodo/rdm-project/issues/548
Landing page:
Request page:

ui: add mathjax to record details page

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html

Closes https://github.com/zenodo/rdm-project/issues/567
- Additional request from the BLR team: Make URLs in references clickable
- Discussed with Lars: added for all, not only BLR

lp references: urlize references

---

invenio_app_rdm/config.py

* Changes resolvers to use existing resolvers build for requests instead of resolvers that use the service layer.

config: harmonize resolvers for notifications

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/CommunitiesManagement.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js

* closes https://github.com/zenodo/zenodo-rdm/issues/717

landing page: highlight verified community in communities list

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/DisplayPartOfCommunities.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/DisplayVerifiedCommunity.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/ComputerTabletUploadsItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/MobileUploadsItem.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides

* closes https://github.com/zenodo/zenodo-rdm/issues/716
General search:
My dashboard:
My dashboard mobile:

search, my dashboard: highlight verified community

---

invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html

Currently, submenus on the user dashboard are *always* shown, ignoring submenus' `.visible` setting.
In all other invenio templates that make use of `flask_menu`, this setting is honored, e.g. [here](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html#L83) and [here](https://github.com/inveniosoftware/invenio-communities/blob/master/invenio_communities/templates/semantic-ui/invenio_communities/details/header.html#L132) (note the `if item.visible` part in those).
With this PR, submenus on the user dashboard will respect this setting too.
This change won't affect behavior of the default-configuration, as the user dashboard's submenus [are registered without passing …

dashboard: respect flask-menu items' visibility

---

invenio_app_rdm/config.py
setup.cfg

This makes them available by default in any invenio-app-rdm backed instance.
:warning: depends on https://github.com/inveniosoftware/invenio-previewer/pull/194
being merged and released (i.e. wait for that to confirm dependency versioning too)

enable audio/video previewer [+]

---

invenio_app_rdm/config.py

Update flask-limiter config according to [invenio-app](https://github.com/inveniosoftware/invenio-app/blob/master/invenio_app/ext.py#L123C25-L123C46). The change in the latter keeps backwards compatibility. This PR fixes the ability to be able to use the newly created config as currently invenio-app-rdm sets a default to a local redis storage.

config: update limiter config

---

invenio_app_rdm/ext.py

If the community is not branded then the "Records" tab doesn't show up as first.

ext: add records menu as first if no branded community

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCitationField.js

If there are DOI links serialized in the citation text, they should be clickable links (cc @tmorrell).
Before:
After:

records-ui: urlize links in citation text

---

invenio_app_rdm/config.py
invenio_app_rdm/theme/views.py
tests/test_views.py

* Introduced `APP_RDM_PAGES` dict in `config.py` to register static pages that can be overridden on the instance level.
* Added `add_static_page_routes` in `views.py` to dynamically add page routes based on the `APP_RDM_PAGES` configuration.
* Created unit tests in `test_views.py`.
**Reminder** …

Views: Add Static Pages dynamic Routing

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/DisplayVerifiedCommunity.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/frontpage/RecordsList.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/AccessRequestForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/timeline/overrides/TimelineFeedHeader.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/ComputerTabletUploadsItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/MobileUploadsItem.js

Every pull request in this repository shows inline ESLint annotations for these 4 problems:
* 'SomeComponent' is defined but never used
* 'someVariable' is assigned a value but never used
* Do not use Array index in keys
* Fragments should contain more than one child - otherwise, there’s no need for a Fragment at all
This pull requests solves the ~~3~~ 4 first issues.
~~The 4th issue will be fixed by https://github.com/inveniosoftware/eslint-config-invenio/pull/16.~~
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an …

Fix ESLint problems

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordVersionsList.js

Opening the landing page of any record currently fetches 4 times the list of versions from the API:
---
---
The problem is due to the `fetchVersions` and `cancellableFetchVersions` (wrongly named `cancellableFetchCitation`) functions being recreated at every render (when the state changes).
This pull request moves the fetching functions inside `useEffect`, so that they are created only within the scope of `useEffect` and don't need to be declared as a dependency. The version is now only fetched once (since the props on which `recordDeserialized.links.versions` and `recid` don't change).
* If you have added [third-party code (copy/pasted or new …

fix: RecordVersionsList fetch versions only once

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/deposit.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/manage_menu.html
invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/ShareDraftButton.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/index.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordManagement.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchResultContainer.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsersGroups/AccessUsersGroups.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsersGroups/UserGroupAccessSearchResultItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/ShareButton.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/ShareModal.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/index.js

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2667
* closes https://github.com/zenodo/zenodo/issues/151
Updated dropdowns:
Share button on the deposit form:
enabled:
disabled:

deposit form: add sharing of drafts

---

invenio_app_rdm/config.py
setup.cfg

* Fixes inveniosoftware/invenio-vocabularies#311
* Fixes inveniosoftware/invenio-vocabularies#333
* Configures the common ROR readers defined in inveniosoftware/invenio-vocabularies#315
* **Needs the aforementioned pull request in `invenio-vocabularies` to be released** for the CI to be green.
* ~~Once merged, the changes in inveniosoftware/invenio-vocabularies#320 should work.~~
* Once merged, the changes in inveniosoftware/invenio-vocabularies#331 should work.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an …

config: vocabularies Datastream common ROR readers

---

CHANGES.rst
invenio_app_rdm/__init__.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities_items/ComputerTabletCommunitiesItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/communities_items/MobileCommunitiesItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/requests.js

* Port fixes for HTML rendering to v11
CI is failing due to changes in `Flask-Mail`. This should be fixed by https://github.com/inveniosoftware/invenio-mail/pull/64
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2693

ui: fix html rendering

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides

Having long community names in German names often overlap the boundaries of the container. Changing height to min-height allows the container to grow if the community name is longer.
**Reminder**
1. You license your contribution under …

Change container height to min-height for responsiveness

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/draft_not_found.html
invenio_app_rdm/records_ui/views/__init__.py
invenio_app_rdm/records_ui/views/records.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/CreateAccessLink.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchResultContainer.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/ShareModal.js

* introduce an error handler and a jinja template for drafts not found when published record exists
* gray out "can view" permission in share drafts
* rework links that are being copied in links tab
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2694
Previews:
Draft not found error page:
Dropdown with grayed out "view" option and the explanation
Flow:

ui: rework secret links tab

---

invenio_app_rdm/config.py

* Fixes inveniosoftware/invenio-vocabularies#324
* Configures the awards readers defined in inveniosoftware/invenio-vocabularies#326
* :heavy_check_mark: Needs the aforementioned pull request to be released for the CI to be green.
* ~~Once merged, the changes in inveniosoftware/invenio-vocabularies#328 should work.~~
* Once merged, we could use it in a celery task (similar to what has been done in inveniosoftware/invenio-vocabularies#331)
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an …

config: vocabularies Datastream awards readers

---

invenio_app_rdm/cli.py

* Skips services that don't implement the rebuild_index method, often because they inherit some record service features but don't handle records
* closes #2741

cli: improve rebuild indices command

---

invenio_app_rdm/records_ui/views/records.py
invenio_app_rdm/requests_ui/views/requests.py

closes https://github.com/inveniosoftware/invenio-swh/issues/23
* Pass record API object to external resources, allowing resources display to be behin permission checks
* Added record return to _resolve_topic_record

ui: pass record API object to external resources

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/creatibutors.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html

* since one macro is used for contributor and creator the link is set to
creators.
* this has been fixed now with an additional parameter
NOTE:
fixes https://github.com/inveniosoftware/invenio-app-rdm/issues/2247

fix(landing-page): link to contributor search

---

setup.cfg

invenio-cache >= 1.3.0 is needed in InvenioRDM v12+ for invenio-vocabularies for example (see https://github.com/inveniosoftware/invenio-vocabularies/blob/master/invenio_vocabularies/services/facets.py#L12 ) .
This should be backported to maint-v12 when accepted. I can do that then or wait for more patches to come in since the workaround is to specify invenio-cache >= 1.3.0 in instance's Pipfile.

dependencies: bump invenio-cache minimum for v12+

---

invenio_app_rdm/config.py

Partially fixes inveniosoftware/invenio-vocabularies#382
The pull request #2755 imported vocabularies readers, transformers, writers consistently.
I found that the affiliations readers was forgotten and not imported; this pull requests fills in this gap.
Currently, [`VOCABULARIES_DATASTREAM_READERS` is empty](https://github.com/ptamarit/invenio-vocabularies/blob/master/invenio_vocabularies/contrib/affiliations/datastreams.py#L49-L50), but I might define affiliations-specific readers as part of inveniosoftware/invenio-vocabularies#382.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commit …

config: import affiliations vocabulary readers

---

invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py

This is a convenience for automated upgrades to be able to detect
errored command from the outside.

migrate to v12: emit non-zero exit code on error

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/container.overrides

> The behavior described in this issue can also be observed on Zenodo. An example is the following record: https://zenodo.org/records/11170937
The `.with-submenu` class includes a `padding-bottom` that, depending on the logo, can bring it closer to the bottom of the gray box:
The default community logo is also affected by this issue:
This PR addresses the issue by removing the `padding-bottom` from the `.with-submenu` class. The figure below shows the behavior after the proposed change.
Also, the GIF below presents the modified version on multiple devices:
* If you have added [third-party code (copy/pasted or new …

theme: adjust padding for community logo on record landing page

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessUsersGroups/AccessUsersGroups.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/ShareModal.js

Records may have no owner (`owned_by` undefined on the frontend) when the record has been created by the system. This PR accounts for that + simplify count computation on tabs.
before:
[no_owner.webm](https://github.com/user-attachments/assets/5c3e5e71-b084-4293-9a14-53b99365d516)
after the modal opens as it's supposed to.

share-modal: account for system created records

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js

Some of the `<Overridable>` components have been using values that weren't passed as props.
This makes it hard to provide overrides for those components that are functionally the same.
For example, I am writing an override for the `InvenioAppRdm.Deposit.CardDepositStatusBox.container` for [`Invenio-Curations`](https://github.com/tu-graz-library/invenio-curations/) which adds a section for the curation review request.
Without passing the props, this override couldn't access the `props.permissions` which is used by the default component to enable/disable some buttons.
With the props being passed, I can use it as expected:

Deposit form: Provide props to overridable components

---

invenio_app_rdm/upgrade_scripts/migrate_11_0_to_12_0.py

Previously, the script would create a new concept DOI for each record but never actually mint them on DataCite.
The [`TaskOp` part from the PIDs service component](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/components/pids.py#L204) was missing, which called the [`register_or_update_pid` task](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/pids/tasks.py#L17).

Upgrade script: Mint the new concept DOI for each upgraded record

---

invenio_app_rdm/config.py

- Depends on https://github.com/inveniosoftware/invenio-stats/pull/149 and https://github.com/inveniosoftware/invenio-rdm-records/pull/1803

config: filter out robots and flag machines

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/communityRecordsSearch/index.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/DisplayPartOfCommunities.js

- Fix: overridable id for community `RecordsResultsListItem.layout` wasn't namespaced because lack of `appName` 
- Fix: `Warning: Each child in a list should have a unique "key" prop.`

search-result: fix issues

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/search/SearchResultItemLayout.js

admin-records: account for system owned records

---

invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js

depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/1768
closes #2732 
Provide `can_publish` permission when rendering the deposit page. Also reordered the permission alphabetically.
Front end check is performed in: https://github.com/inveniosoftware/invenio-rdm-records/pull/1768
With permission:
Without permission:
**Frontend** …

deposit: provide and check publish permission for visibility

---

CHANGES.rst
invenio_app_rdm/__init__.py
setup.cfg

GuestAccessNotifications are directly imported from invenio-rdm-records which only have been added in v10.7.0.
Encountered this issue when setting up an instance with another package which had very loose dependencies (no upper pin of any package). v10.0.0 of rdm-records was installed, which still satisfied the current restriction but led to an error down the way when importing guest access notifications in `setup.cfg`, which have been added in v10.7.0.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an …

deps: raise lower pin of invenio-rdm-records

---

invenio_app_rdm/communities_ui/templates/semantic-ui/invenio_communities/details/browse/index.html
invenio_app_rdm/communities_ui/views/communities.py
invenio_app_rdm/communities_ui/views/ui.py
invenio_app_rdm/config.py
invenio_app_rdm/ext.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/subcommunity/browse.js
invenio_app_rdm/theme/webpack.py

Close https://github.com/zenodo/zenodo-rdm/issues/990
**Frontend**
**Reminder** …

feat: create browse communities page

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/base.js
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/page.html

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/198

search results: render Mathjax in the results list

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/ComputerTabletUploadsItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/MobileUploadsItem.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/views/item.overrides

* addresses mathjax formulas truncation
Forced overflow (formula simply is hidden):
before forcing the overflow

assets: fix item description overflow issue

---

CHANGES.rst
invenio_app_rdm/__init__.py

Also adding missing changelog from `v13.0.0b1.dev10`.

📦 release: v13.0.0b1.dev11

---

invenio_app_rdm/communities_ui/templates/semantic-ui/invenio_communities/collections/collection.html
invenio_app_rdm/communities_ui/templates/semantic-ui/invenio_communities/collections/macros.html
invenio_app_rdm/communities_ui/templates/semantic-ui/invenio_communities/details/browse/index.html
invenio_app_rdm/communities_ui/views/communities.py
invenio_app_rdm/config.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/subcommunity/browse.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/searchbar.html

closes https://github.com/zenodo/zenodo-rdm/issues/1006
---
--- 
---

Add collections browse

---

invenio_app_rdm/communities_ui/templates/semantic-ui/invenio_communities/collections/collection.html
invenio_app_rdm/communities_ui/templates/semantic-ui/invenio_communities/collections/macros.html
invenio_app_rdm/communities_ui/views/communities.py

Closes Issue https://github.com/inveniosoftware/invenio-communities/issues/1227
##
**Frontend**
**Reminder**
2. You agree …

ui: passing collections to communities_home

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/DisplayPartOfCommunities.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js

Partially fixes inveniosoftware/invenio-communities#1234
Second iteration on changes in #2883
* Not relying on the verified field which is not serialized for non admins
* Showing an icon next to parent communities too
* Deterministic sorting of communities
**Frontend**
**Reminder** …

communities-ui: verified icon display logic change and deterministic sorting

---

invenio_app_rdm/administration/records/records.py

f15917601e94c9c8c52576cfa2044eb4d819aa9b introduced lowercase records in the sidebar 
This PR adds `menu_label` with the correct case. After:
The order has been swapped, but I think it is preferable in this order
**Frontend**
**Reminder** …

chore: fix typo

---

invenio_app_rdm/administration/records/records.py
invenio_app_rdm/administration/user_moderation/user_moderation.py
invenio_app_rdm/administration/users/users.py

Close [#2899](https://github.com/inveniosoftware/invenio-app-rdm/issues/2899)
Setting default_size and pagination_options as changing in invenio-search-ui would change it everywhere including non-admin pages
Removing `size` as it isn't an [accepted parameter](https://github.com/inveniosoftware/invenio-search-ui/blob/master/invenio_search_ui/searchconfig.py#L94) and therefore not used and `page=1` as this is the [default](https://github.com/inveniosoftware/invenio-search-ui/blob/master/invenio_search_ui/searchconfig.py#L87)
* If you have added [third-party code (copy/pasted or new …

admin: change default # of results from 10 to 20

---

invenio_app_rdm/records_ui/views/deposits.py

context: migrate to flask >= 3.0
- fix: remove DeprecationWarning for sqlalchemy
- setup: remove flask upper pin
* the sqlalchemy commit is here because without upgrading sqlalchemy it is not possible to go to flask >= 2.3
* the remove of invenio-admin is not part of the migration to flask >= 3.0 because the problem with the app.before_first_request has been fixed in invenio-admin. nevertheless the PR for it should be merged!

remove flask upper pin

---

invenio_app_rdm/records_ui/views/deposits.py

In order to fix https://github.com/inveniosoftware/invenio-rdm-records/issues/1846 this passes `current_app.config["APP_RDM_USER_DASHBOARD_ROUTES"]["uploads"]` to the deposit form react app.
**Reminder**
1. You …

pass config to deposit_create and deposit_edit

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ManageButton.js

closes https://github.com/zenodo/zenodo-rdm/issues/952

landing_page: add block user option

---

invenio_app_rdm/communities_ui/templates/semantic-ui/invenio_communities/details/browse/index.html
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/subcommunity/browse.js

Children disabled. Before and after:
Children enabled (See all visible in after). Before and after:

bug: add message to browse page when no subcoms

---

invenio_app_rdm/config.py

(Part of) Close https://github.com/inveniosoftware/invenio-app-rdm/issues/2777
Run update domain statistics task every hour. These statistics change when users create accounts, get blocked, etc
We simply never added a task to update these regularly
**Frontend**
**Reminder** …

celery: add update_domain_status task

---

invenio_app_rdm/users_ui/templates/semantic-ui/invenio_app_rdm/users/header.html

Fixes: https://github.com/inveniosoftware/invenio-communities/issues/1209

semantic-ui: users: header: Use endpoints from config

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ManageDefaultBrandingAction/ManageDefaultBrandingAction.js

* Closes #2869.
* Passes "null" instead of empty string ("") as the "default" field
value when removing community branding from a record.

records-ui: fix removing community branding

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/ComputerTabletUploadsItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads_items/MobileUploadsItem.js

Fixes #2919
See description in the linked issue.
**Frontend**
**Reminder**
2. You agree that you have the right to …

fix: ui: escape journal title once

---

invenio_app_rdm/theme/webpack.py

This is part of the effort to make the `CopyWebpackPlugin` patterns configurable, to address the feedback in the PDF.js PR: https://github.com/inveniosoftware/invenio-previewer/pull/203
Requires https://github.com/inveniosoftware/invenio-assets/pull/173 and https://github.com/inveniosoftware/pywebpack/pull/45

Webpack: Configure copy patterns for TinyMCE

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/meta.html

Landing pages never have a `<meta name="citation_author" content="..." />` because the way of extracting the creators is not valid.
This pull request fixes this.
**Frontend**
**Reminder** …

fix: meta: add missing HighWire authors

---

invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/collections/message.overrides

*closes https://github.com/CERNDocumentServer/cds-rdm/issues/163
Before:
After:

theme: put banner message below other objects

---

invenio_app_rdm/ext.py
invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/index.js

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/163

doi: handle UI for optional DOI feature

---

invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/description.html

[Error 26](https://validator.w3.org/nu/?doc=https%3A%2F%2Fsandbox.zenodo.org%2Frecords%2F143232) is because we wrap the description in a `<p>` tag, but the paragraph tag can't contain HTML like lists or paragraphs. The HTML of the page is 
```html
<section id="description" class="rel-mt-2 rich-input-content" aria-label="Record description">
<h2 id="description-heading" class="sr-only">Description</h2>
<div style="word-wrap: break-word;">
<p>
<ul>
<li>One list item</li>
</ul>
</p>
</div>
</section>
```
With paragraphs we still get [Error 26
](https://validator.w3.org/nu/?doc=https%3A%2F%2Fsandbox.zenodo.org%2Frecords%2F143235) with similar html
```html
<section id="description" class="rel-mt-2 …
```

bug: remove unnecessary <p> tag

---

invenio_app_rdm/administration/records/records.py
invenio_app_rdm/config.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/CompareRevisionsDropdown.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/ImpersonateUserForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/RevisionsDiffViewer.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/CompareRevisions.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RecordResourceActions.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/api/api.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/api/routes.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/administration_page.html
invenio_app_rdm/theme/webpack.py

requires https://github.com/inveniosoftware/invenio-rdm-records/pull/1929
requires https://github.com/inveniosoftware/invenio-administration/pull/233
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2968

administration: compare record revisions

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js

* Closes https://github.com/CERNDocumentServer/cds-rdm/issues/312

resultList: Add overridable descriptio

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RecordResourceActions.js
invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/elements/label.overrides

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/322
Before:
After:

ui: make some css more important

---

invenio_app_rdm/records_ui/views/decorators.py
invenio_app_rdm/records_ui/views/records.py
tests/ui/test_signposting_ui.py

* Fixes #2937
* Depends on inveniosoftware/invenio-rdm-records#1908
* See description in linked ticket
**Frontend**
**Reminder** …

views: FAIR signposting level 1 support (HTTP Link headers)

---

invenio_app_rdm/urls.py

* Bug fixes #2937
* Causing `TypeError: http header must be encodable in latin1` (might be a problem since Flask v3 only)
* Related to changes in Flask v3 changes in zenodo/zenodo-rdm#1122 and inveniosoftware/invenio-files-rest@a419808c16617125590381b7dc02f41ca49359b2

views: signposting: files: fix filename encoding issues for downloads

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/CompareRevisionsDropdown.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/RevisionsDiffViewer.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/CompareRevisions.js
run-js-linter.sh

* warning propType "diff" is not required, but has no corresponding
defaultProps declaration
* warning propType "srcRevision" is not required, but has no
corresponding defaultProps declaration
* warning propType "targetRevision" is not required, but has no
corresponding defaultProps declaration
* warning fetchRevisions should be placed after componentWillUnmount
* warning 'diff' is assigned a value but never used
* warning Must use destructuring state assignment
* apply indentation to run-js-linter.sh with only spaces

fix: eslint warnings

---

invenio_app_rdm/requests_ui/templates/semantic-ui/invenio_requests/community-submission/index.html
invenio_app_rdm/requests_ui/views/requests.py

* Fixes https://github.com/zenodo/zenodo-rdm/issues/1133
* See linked issue for description and screenshot
**Frontend**
**Reminder** …

checks: add check tab

---

invenio_app_rdm/requests_ui/views/requests.py

* Fixes https://github.com/zenodo/zenodo-rdm/issues/1133
A bug causing requests like https://sandbox.zenodo.org/communities/sandbox-open-data/requests/42140fd7-8471-42f8-b73b-a886b2009f44 to fail with `TypeError: 'NoneType' object is not subscriptable` on:
```python
communities.append(community.id)
if is_record_inclusion:
record_uuid = current_rdm_records_service.record_cls.pid.resolve(
record["id"]
).id
```
2 other methods `_resolve_record_or_draft_files` and `_resolve_record_or_draft_media_files` are also doing `record_pid = record["id"]`, but the parameter passed to these methods is `record_ui`, not on `record`.

checks: add checks tab to requests (fix record ID retrieval)

---

invenio_app_rdm/administration/records/records.py
invenio_app_rdm/administration/user_moderation/user_moderation.py
invenio_app_rdm/administration/users/users.py
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/detail.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/access-form.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/contact.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/side_bar/licenses.html
invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/version.html
invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/ImpersonateUser.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/components/ImpersonateUserForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/RestoreConfirmation.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/records/TombstoneForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/administration/userModeration/search/SearchResultItemLayout.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/components/RecordsResultsListItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/AccessRequestForm.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/RecordCommunitiesList.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/ShareOptions/AccessLinks/LinksSearchItem.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/theme.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/user_dashboard/uploads.js
invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/utils.js
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/files_integrity_report/email/files_integrity_report.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/footer.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/header.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/intro_section.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/macros/records_list.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/settings/notifications.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/site_footer.html
invenio_app_rdm/theme/templates/themes/default/invenio_app_rdm/site_footer.html

Add missing translations
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution …

i18n: add missing translation

---

invenio_app_rdm/records_ui/views/__init__.py

This is relevant for the case when sharing access to files for unpublished drafts.
Given there is a draft `87ra6-2bs54` with the file `TU Wien Research Data - 2025.pdf` and the user has access to the draft, then...
Accessing the URL `https://localhost:5000/records/87ra6-2bs54/files/TU Wien Research Data - 2025.pdf?download=1&preview=1` works fine – the file is downloaded as expected.
However, if the `preview=1` flag is omitted from the URL, then it breaks apart with a `500 internal server error` response. :boom: 
Since at TUW we're sending emails about unhandled exceptions to admins, this spams our inbox with this sort of errors.

records-ui: add error handler for `NoResultFound` exceptions

---

tests/ui/conftest.py
tests/ui/test_file_download.py

* add tests for file download url with and without preview flag
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/3036
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the current …

test: add tests for file download with and without preview flag

---

invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/landing_page/theme.js

Fix cite all version DOI badge click not working

semantic-ui: landing_page: add click event for cite all versions

---

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/macros/records_list.html

**This is an alternative fix for #3117** (thanks for opening this @mfenner!)
---
* The `records_list` macro was importing `invenio-app-rdm-frontpage.js` early, before any other component-specific JS was imported. This is necessary, as the macro can be used in a range of places, so we need to make sure its associated JS is imported wherever it is used.
* Since we were importing this JS before `overridable-registry`, the loop to add the overriden components to the singleton store: https://github.com/inveniosoftware/invenio-app-rdm/blob/979d6ab4c84fffaa8c70b2b32a40efac179bfd98/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/overridableRegistry/index.js#L11-L13 was being run _after_ the frontpage JS ran the `getAll` function on the store. This meant user-specified overrides were …

fix: import `overridable-registry.js` in `records_list` macro

---

invenio_app_rdm/records_ui/views/decorators.py
invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/records_ui/views/records.py

The themed deposit form expected `community_ui` to be passed, but it was only passed as `community`

fix(deposits): pass community_ui to the themed deposit form

---

invenio_app_rdm/config.py
invenio_app_rdm/fixtures/pages.py
invenio_app_rdm/records_ui/views/deposits.py
invenio_app_rdm/records_ui/views/records.py

- **fixtures: allow specifying `template_name` in page fixtures**
- **pages: add community base template as a valid option**
- **fix(views): use correct community value**
* After the change in 33f1b0d2, values passed to the UI or used for
accessing UI-related attributes (e.g. the "theme"), must come from
the community UI-serialized value instead of the service result item.

community value fixes

---

invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.de.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.en.html
invenio_app_rdm/theme/templates/semantic-ui/invenio_app_rdm/help/search.sv.html

The current search help doesn't include the correct capitalization for NOT to find missing fields. 
example (too many results): https://zenodo.org/search?q=not%20_exists_%3Ametadata.description&l=list&p=1&s=10&sort=bestmatch
correct: https://zenodo.org/search?q=NOT%20_exists_%3Ametadata.description&l=list&p=1&s=10&sort=bestmatch
**Reminder** …

help: correct search instructions for missing fields

---

CHANGES.rst
invenio_app_rdm/__init__.py
invenio_app_rdm/records_ui/views/deposits.py

Fix deposit form DOI handling from https://github.com/inveniosoftware/invenio-rdm-records/pull/2166
**Frontend**
**Reminder**
2. You agree that you …

Backport and release v13

---

invenio_app_rdm/config.py
invenio_app_rdm/records_ui/views/deposits.py

Makes sorting by `last_reply` possible in the user's request dashboard.
Related:
* inveniosoftware/invenio-requests#485
* inveniosoftware/invenio-rdm-records#2168

feat: config: add last reply sort option
